const pairs={BTCUSDT:{name:'Bitcoin',icon:'₿',class:'btc',fallback:58420,precision:2},SOLUSDT:{name:'Solana',icon:'S',class:'sol',fallback:130.14,precision:2},SEIUSDT:{name:'Sei',icon:'S',class:'sei',fallback:.0558,precision:4}};
const signalLevels={SEIUSDT:{entry:.0561,tp:.053,sl:.0565,side:'short'},SOLUSDT:{entry:129,tp:134,sl:124,side:'long'}};
let active='BTCUSDT',candles=[],socket=null,lang='ru',lastPrice=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const dict={en:{marketLive:'Market live',demoSignal:'New signal',markets:'Markets',signals30:'Signals / 30d',virtualBalance:'Virtual balance',openPnl:'Open PnL',positions:'positions',profitFactor:'Profit factor',maxDrawdown:'Max drawdown',loading:'Loading market…',activeSignal:'Active signal',price:'Price',openPositions:'Open positions',history:'History →',liveSignals:'Signals',autoTrading:'Auto trades',paperOnly:'Paper only',riskText:'Risk 1% · Leverage from signal',now:'now',disclaimer:'Paper trading only. Not financial advice.',newSignal:'NEW SIGNAL',tapOpen:'Tap to open chart'},ru:{marketLive:'Рынок онлайн',demoSignal:'Новый сигнал',markets:'Рынки',signals30:'Сигналов / 30д',virtualBalance:'Виртуальный баланс',openPnl:'Открытый PnL',positions:'позиции',profitFactor:'Profit factor',maxDrawdown:'Макс. просадка',loading:'Загрузка рынка…',activeSignal:'Активный сигнал',price:'Цена',openPositions:'Открытые позиции',history:'История →',liveSignals:'Сигналы',autoTrading:'Автосделки',paperOnly:'Только виртуально',riskText:'Риск 1% · Плечо из сигнала',now:'сейчас',disclaimer:'Виртуальная торговля. Не финансовая рекомендация.',newSignal:'НОВЫЙ СИГНАЛ',tapOpen:'Нажмите, чтобы открыть график'}};
function format(n,p=2){return Number(n).toLocaleString(lang==='ru'?'ru-RU':'en-US',{minimumFractionDigits:p,maximumFractionDigits:p})}
async function loadPair(pair){active=pair;const meta=pairs[pair];$$('.coin,.signal').forEach(x=>x.classList.toggle('active',x.dataset.pair===pair));$('#pairName').innerHTML=`${meta.name} <small>${pair.replace('USDT','')} / USDT</small>`;$('#pairIcon').className=`coin-icon ${meta.class}`;$('#pairIcon').textContent=meta.icon;$('#signalBadge').classList.toggle('hidden',!signalLevels[pair]);$('#chartLoading').classList.remove('hidden');if(socket)socket.close();
  const start=performance.now();try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${pair}&interval=15m&limit=70`);if(!r.ok)throw Error();const rows=await r.json();candles=rows.map(x=>({t:x[0],o:+x[1],h:+x[2],l:+x[3],c:+x[4]}));$('#feedStatus').textContent='BINANCE · LIVE';$('#latency').textContent=Math.round(performance.now()-start)+' ms'}catch(e){candles=mock(meta.fallback);$('#feedStatus').textContent='DEMO DATA';$('#latency').textContent='offline'}
  updatePrice(candles.at(-1).c);$('#chartLoading').classList.add('hidden');draw();connect(pair)}
function mock(base){let v=base;return Array.from({length:70},(_,i)=>{const o=v;v*=1+(Math.random()-.48)*.008;return{t:Date.now()-(70-i)*9e5,o,h:Math.max(o,v)*(1+Math.random()*.003),l:Math.min(o,v)*(1-Math.random()*.003),c:v}})}
function connect(pair){try{socket=new WebSocket(`wss://stream.binance.com:9443/ws/${pair.toLowerCase()}@kline_15m`);socket.onmessage=e=>{const k=JSON.parse(e.data).k,bar={t:k.t,o:+k.o,h:+k.h,l:+k.l,c:+k.c};if(candles.at(-1)?.t===bar.t)candles[candles.length-1]=bar;else{candles.push(bar);candles=candles.slice(-70)}updatePrice(bar.c);draw()}}catch(e){}}
function updatePrice(p){lastPrice=p;const m=pairs[active],first=candles[0]?.o||p,change=(p/first-1)*100;$('#livePrice').textContent='$'+format(p,m.precision);$('#liveChange').textContent=`${change>=0?'+':''}${change.toFixed(2)}%`;$('#liveChange').className=change>=0?'green':'red';const key=active.slice(0,-4).toLowerCase();const pe=$(`#${key}Price`),ce=$(`#${key}Change`);if(pe){pe.textContent='$'+format(p,m.precision);ce.textContent=`${change>=0?'+':''}${change.toFixed(2)}%`;ce.className=change>=0?'green':'red'}}
function draw(){const c=$('#chart'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);const W=r.width,H=r.height,pad={l:46,r:68,t:26,b:28};const levels=signalLevels[active];let lo=Math.min(...candles.map(v=>v.l)),hi=Math.max(...candles.map(v=>v.h));if(levels){lo=Math.min(lo,levels.entry,levels.tp,levels.sl);hi=Math.max(hi,levels.entry,levels.tp,levels.sl)}const span=(hi-lo)||1;lo-=span*.06;hi+=span*.06;const y=v=>pad.t+(hi-v)/(hi-lo)*(H-pad.t-pad.b);const gap=(W-pad.l-pad.r)/candles.length,body=Math.max(2,gap*.56);
  candles.forEach((v,i)=>{const cx=pad.l+i*gap+gap/2,up=v.c>=v.o,col=up?'#72e6b7':'#f16d7d';x.strokeStyle=col;x.lineWidth=1;x.beginPath();x.moveTo(cx,y(v.h));x.lineTo(cx,y(v.l));x.stroke();x.fillStyle=col;x.fillRect(cx-body/2,Math.min(y(v.o),y(v.c)),body,Math.max(1,Math.abs(y(v.o)-y(v.c))))});
  [[lastPrice,'#8b97ad','PRICE'],...(levels?[[levels.entry,'#a88bff','ENTRY'],[levels.tp,'#78edbd','TP'],[levels.sl,'#ff6f82','SL']]:[])].forEach(([v,col,label])=>{const yy=y(v);x.save();x.strokeStyle=col;x.globalAlpha=.72;x.setLineDash(label==='PRICE'?[3,4]:[7,5]);x.beginPath();x.moveTo(pad.l,yy);x.lineTo(W-pad.r+5,yy);x.stroke();x.restore();x.fillStyle=col;x.font='10px Space Mono';x.fillText(`${label} ${format(v,pairs[active].precision)}`,W-pad.r+8,yy+3)});
  x.fillStyle='#667189';x.font='9px Space Mono';for(let i=0;i<5;i++){const idx=Math.floor(i*(candles.length-1)/4),date=new Date(candles[idx].t);x.fillText(date.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),pad.l+idx*gap,H-9)}}
function simulate(){const t=$('#toast');t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),7000)}
$$('[data-pair]').forEach(el=>el.addEventListener('click',()=>loadPair(el.dataset.pair)));$('#simulate').onclick=simulate;$('#toast').onclick=e=>{if(e.target.tagName==='BUTTON')$('#toast').classList.add('hidden');else{loadPair('SEIUSDT');$('#toast').classList.add('hidden')}};$('#lang').onclick=()=>{lang=lang==='ru'?'en':'ru';document.documentElement.lang=lang;$('#lang').textContent=lang==='ru'?'EN':'RU';$$('[data-i18n]').forEach(e=>e.textContent=dict[lang][e.dataset.i18n]);draw()};$$('.timeframes button').forEach(b=>b.onclick=()=>{$$('.timeframes button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});window.addEventListener('resize',draw);loadPair('BTCUSDT');setTimeout(simulate,2600);
