"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {onAuthStateChanged,signInWithPopup,signOut,User} from "firebase/auth";
import {addDoc,collection,deleteDoc,doc,getDoc,serverTimestamp,setDoc} from "firebase/firestore";
import {auth,db,googleProvider,OWNER_EMAIL} from "./firebase";
import {Bell,BriefcaseBusiness,Check,ChevronDown,CircleUserRound,Download,Hammer,Languages,LocateFixed,MapPin,MessageCircle,Plus,Search,ShieldCheck,SlidersHorizontal,Sparkles,Star,UserRound,Users,Volume2,Wrench,X} from "lucide-react";
type Lang="ru"|"lv"|"en"|"uk"; type Role="customer"|"master";
const copy={
ru:{map:"Карта",orders:"Заявки",masters:"Мастера",search:"Что нужно сделать?",newOrder:"Создать заявку",near:"Рядом с вами",urgent:"Срочные заявки",all:"Все услуги",response:"Откликнуться",from:"от",login:"Войти через Google",install:"Скачать приложение",roleC:"Я заказчик",roleM:"Я исполнитель",sound:"Звуки включены",titleC:"Найдите мастера рядом",titleM:"Новые заказы рядом",subC:"Опишите задачу — мастера предложат время и цену",subM:"Выберите подходящую работу и отправьте предложение",admin:"Админ-панель",addMod:"Добавить модератора",users:"Пользователи",moderation:"Модерация"},
lv:{map:"Karte",orders:"Pasūtījumi",masters:"Meistari",search:"Kas jāizdara?",newOrder:"Izveidot pasūtījumu",near:"Jūsu tuvumā",urgent:"Steidzami pasūtījumi",all:"Visi pakalpojumi",response:"Pieteikties",from:"no",login:"Turpināt ar Google",install:"Lejupielādēt lietotni",roleC:"Esmu klients",roleM:"Esmu meistars",sound:"Skaņa ieslēgta",titleC:"Atrodiet meistaru tuvumā",titleM:"Jauni pasūtījumi tuvumā",subC:"Aprakstiet darbu — meistari piedāvās laiku un cenu",subM:"Izvēlieties darbu un nosūtiet piedāvājumu",admin:"Administratora panelis",addMod:"Pievienot moderatoru",users:"Lietotāji",moderation:"Moderācija"},
en:{map:"Map",orders:"Requests",masters:"Pros",search:"What needs doing?",newOrder:"Post a request",near:"Near you",urgent:"Urgent requests",all:"All services",response:"Respond",from:"from",login:"Continue with Google",install:"Install app",roleC:"I'm a customer",roleM:"I'm a professional",sound:"Sounds on",titleC:"Find a pro nearby",titleM:"New jobs nearby",subC:"Describe the task — pros offer a time and price",subM:"Pick a suitable job and send your offer",admin:"Admin panel",addMod:"Add moderator",users:"Users",moderation:"Moderation"},
uk:{map:"Карта",orders:"Заявки",masters:"Майстри",search:"Що потрібно зробити?",newOrder:"Створити заявку",near:"Поруч із вами",urgent:"Термінові заявки",all:"Усі послуги",response:"Відгукнутися",from:"від",login:"Увійти через Google",install:"Завантажити застосунок",roleC:"Я замовник",roleM:"Я виконавець",sound:"Звуки увімкнено",titleC:"Знайдіть майстра поруч",titleM:"Нові замовлення поруч",subC:"Опишіть завдання — майстри запропонують час і ціну",subM:"Оберіть роботу та надішліть пропозицію",admin:"Адмін-панель",addMod:"Додати модератора",users:"Користувачі",moderation:"Модерація"}}
const services=[{icon:"🔧",ru:"Сантехник",lv:"Santehniķis",en:"Plumber",uk:"Сантехнік"},{icon:"🧱",ru:"Плиточник",lv:"Flīzētājs",en:"Tiler",uk:"Плиточник"},{icon:"💡",ru:"Электрик",lv:"Elektriķis",en:"Electrician",uk:"Електрик"},{icon:"🪛",ru:"Сборка мебели",lv:"Mēbeļu montāža",en:"Furniture assembly",uk:"Збірка меблів"},{icon:"🎨",ru:"Маляр",lv:"Krāsotājs",en:"Painter",uk:"Маляр"},{icon:"🧹",ru:"Уборка",lv:"Uzkopšana",en:"Cleaning",uk:"Прибирання"}];
const jobs=[{title:{ru:"Установить смеситель",lv:"Uzstādīt maisītāju",en:"Install a mixer tap",uk:"Встановити змішувач"},place:"Purvciems",price:"€35–50",time:"Сегодня, 18:00",urgent:true,x:68,y:36},{title:{ru:"Собрать шкаф IKEA",lv:"Salikt IKEA skapi",en:"Assemble IKEA wardrobe",uk:"Зібрати шафу IKEA"},place:"Centrs",price:"€55–75",time:"Завтра",urgent:false,x:46,y:46},{title:{ru:"Положить плитку 12 м²",lv:"Ieklā flīzes 12 m²",en:"Tile 12 m²",uk:"Покласти плитку 12 м²"},place:"Imanta",price:"€240–320",time:"На этой неделе",urgent:false,x:24,y:54},{title:{ru:"Повесить 3 светильника",lv:"Uzstādīt 3 gaismekļus",en:"Install 3 lights",uk:"Повісити 3 світильники"},place:"Teika",price:"€45–65",time:"Сегодня",urgent:true,x:59,y:24}];
const pros=[{name:"Artūrs K.",skill:"Сантехника · мелкий ремонт",rating:"4.9",jobs:86,place:"Purvciems",price:"€25/ч",initials:"AK"},{name:"Maksims R.",skill:"Мебель · установка",rating:"4.8",jobs:54,place:"Pļavnieki",price:"€22/ч",initials:"MR"},{name:"Oleh S.",skill:"Плитка · ванная",rating:"5.0",jobs:31,place:"Centrs",price:"€28/ч",initials:"OS"}];
function ping(){try{const AC=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext,c=new AC(),o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.16)}catch{}}
export default function Home(){
const[lang,setLang]=useState<Lang>("ru"),[role,setRole]=useState<Role>("customer"),[query,setQuery]=useState(""),[modal,setModal]=useState<"login"|"order"|"admin"|null>(null),[toast,setToast]=useState(""),[mods,setMods]=useState<string[]>([]),[modEmail,setModEmail]=useState(""),[user,setUser]=useState<User|null>(null),[isModerator,setIsModerator]=useState(false),[busy,setBusy]=useState(false);
const t=copy[lang];const filtered=useMemo(()=>services.filter(s=>s[lang].toLowerCase().includes(query.toLowerCase())),[query,lang]);const notify=(m:string)=>{setToast(m);ping();setTimeout(()=>setToast(""),2400)};
const isOwner=user?.email?.toLowerCase()===OWNER_EMAIL; const canModerate=isOwner||isModerator;
useEffect(()=>onAuthStateChanged(auth,async next=>{setUser(next);if(!next){setIsModerator(false);return}await setDoc(doc(db,"users",next.uid),{email:next.email,displayName:next.displayName,photoURL:next.photoURL,role,lastSeenAt:serverTimestamp()},{merge:true});const mod=next.email?await getDoc(doc(db,"moderators",next.email.toLowerCase())):null;setIsModerator(Boolean(mod?.exists()))}),[]);
const login=async()=>{try{setBusy(true);await signInWithPopup(auth,googleProvider);setModal(null);notify("Вход выполнен")}catch(e){console.error(e);notify("Не удалось войти через Google")}finally{setBusy(false)}};
const logout=async()=>{await signOut(auth);notify("Вы вышли из аккаунта")};
const saveOrder=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!user){setModal("login");notify("Сначала войдите через Google");return}const f=new FormData(e.currentTarget);try{setBusy(true);await addDoc(collection(db,"orders"),{service:f.get("service"),city:f.get("city"),district:f.get("district"),date:f.get("date"),description:f.get("description"),customerId:user.uid,customerEmail:user.email,status:"open",createdAt:serverTimestamp()});setModal(null);notify("Заявка опубликована")}catch(err){console.error(err);notify("Не удалось сохранить заявку")}finally{setBusy(false)}};
const addModerator=async()=>{const email=modEmail.trim().toLowerCase();if(!isOwner||!email.includes("@"))return;try{await setDoc(doc(db,"moderators",email),{email,addedBy:user?.email,createdAt:serverTimestamp()});setMods(x=>[...new Set([...x,email])]);setModEmail("");notify("Модератор добавлен")}catch(err){console.error(err);notify("Не удалось добавить модератора")}};
const removeModerator=async(email:string)=>{if(!isOwner)return;await deleteDoc(doc(db,"moderators",email));setMods(x=>x.filter(v=>v!==email));notify("Модератор удалён")};
return <main className="app-shell"><header className="topbar"><button className="brand"><span className="brand-mark"><Hammer size={21}/></span><span>MURDILI<b>MAX</b></span></button><nav><button className="active"><MapPin/>{t.map}</button><button><BriefcaseBusiness/>{t.orders}</button><button><Users/>{t.masters}</button></nav><div className="top-actions"><button className="icon-button" onClick={()=>notify(t.sound)}><Volume2/></button><div className="language"><Languages/><select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ru">RU</option><option value="lv">LV</option><option value="en">EN</option><option value="uk">UA</option></select><ChevronDown/></div><button className="login-button" onClick={()=>user?logout():setModal("login")}><CircleUserRound/><span>{user?.displayName||t.login}</span></button></div></header>
<section className="command-panel"><div className="role-switch"><button className={role==="customer"?"active":""} onClick={()=>setRole("customer")}><UserRound/>{t.roleC}</button><button className={role==="master"?"active":""} onClick={()=>setRole("master")}><Wrench/>{t.roleM}</button></div><div className="headline"><div><p className="eyebrow"><Sparkles/> MURDILIMAX · RĪGA</p><h1>{role==="customer"?t.titleC:t.titleM}</h1><p>{role==="customer"?t.subC:t.subM}</p></div><button className="primary" onClick={()=>setModal("order")}><Plus/>{t.newOrder}</button></div><div className="search-row"><label className="searchbox"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label><button className="location"><MapPin/><span>Rīga, Centrs</span><ChevronDown/></button><button className="locate" onClick={()=>notify("Местоположение определено")}><LocateFixed/></button></div><div className="service-strip">{filtered.map(s=><button key={s.en} onClick={()=>{setQuery(s[lang]);notify(`${s[lang]} — выбрано`)}}><span>{s.icon}</span>{s[lang]}</button>)}</div></section>
<section className="workspace"><div className="map-card"><div className="map-toolbar"><div><strong>{t.near}</strong><span>Rīga · 4 km</span></div><button><SlidersHorizontal/>{t.all}</button></div><div className="map-canvas"><div className="river"/><span className="district d1">IMANTA</span><span className="district d2">CENTRS</span><span className="district d3">PURVCIEMS</span><span className="district d4">TEIKA</span><span className="district d5">PĻAVNIEKI</span>{jobs.map((j,i)=><button key={j.place} className={`map-pin ${j.urgent?"urgent":""}`} style={{left:`${j.x}%`,top:`${j.y}%`}} onClick={()=>notify(`${j.title[lang]} · ${j.price}`)}><span>{i+1}</span><em>{j.price}</em></button>)}<div className="map-controls"><button>+</button><button>−</button></div><div className="map-credit">Map · Riga</div></div></div>
<aside className="feed"><div className="section-title"><div><h2>{role==="customer"?t.masters:t.urgent}</h2><p>{role==="customer"?"Проверенные специалисты рядом":"Обновлено только что"}</p></div><button><Bell/></button></div>{role==="master"?jobs.map((j,i)=><article className="job-card" key={j.place}><div className="job-top"><span className={`number ${j.urgent?"hot":""}`}>{i+1}</span><div><h3>{j.title[lang]}</h3><p><MapPin/>{j.place} · {j.time}</p></div><strong>{j.price}</strong></div><button onClick={()=>notify("Заявка добавлена в отклики")}>{t.response}<MessageCircle/></button></article>):pros.map((p,i)=><article className="pro-card" key={p.name}><div className={`avatar a${i}`}>{p.initials}</div><div className="pro-info"><h3>{p.name}<ShieldCheck/></h3><p>{p.skill}</p><div><span><Star fill="currentColor"/>{p.rating}</span><span>{p.jobs} работ</span><span><MapPin/>{p.place}</span></div></div><div className="pro-side"><strong>{t.from} {p.price}</strong><button onClick={()=>notify("Чат с мастером открыт")}><MessageCircle/></button></div></article>)}</aside></section>
<footer><span>© 2026 MURDILIMAX</span><button onClick={()=>notify("Можно установить на главный экран")}><Download/>{t.install}</button>{canModerate&&<button onClick={()=>setModal("admin")}><ShieldCheck/>{t.admin}</button>}</footer>
{modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>
{modal==="login"&&<><div className="modal-icon"><CircleUserRound/></div><h2>{t.login}</h2><p>Один аккаунт для заказов и услуг. Роль можно менять в любое время.</p><button className="google" disabled={busy} onClick={login}><b>G</b>{busy?"Подключение…":t.login}</button><small>Продолжая, вы принимаете условия MURDILIMAX.</small></>}
{modal==="order"&&<form onSubmit={saveOrder}><div className="modal-icon"><Plus/></div><h2>{t.newOrder}</h2><div className="form-grid"><label>Услуга<input name="service" required placeholder="Например, собрать шкаф"/></label><label>Город<select name="city"><option>Rīga</option><option>Jūrmala</option><option>Jelgava</option><option>Liepāja</option><option>Daugavpils</option></select></label><label>Район<select name="district"><option>Centrs</option><option>Purvciems</option><option>Imanta</option><option>Teika</option><option>Pļavnieki</option></select></label><label>Когда<input name="date" type="date" required/></label><label className="wide">Описание<textarea name="description" required placeholder="Коротко опишите задачу"/></label></div><button className="primary wide-button" disabled={busy} type="submit"><Check/>{busy?"Сохраняем…":"Опубликовать бесплатно"}</button></form>}
{modal==="admin"&&canModerate&&<><div className="admin-head"><div className="modal-icon"><ShieldCheck/></div><div><h2>{t.admin}</h2><p>{user?.email} · {isOwner?"владелец":"модератор"}</p></div></div><div className="admin-stats"><div><strong>Firebase</strong><span>{t.users}</span></div><div><strong>Live</strong><span>{t.orders}</span></div><div><strong>Secure</strong><span>{t.moderation}</span></div></div>{isOwner&&<><h3>{t.addMod}</h3><div className="add-mod"><input value={modEmail} onChange={e=>setModEmail(e.target.value)} placeholder="moderator@gmail.com"/><button onClick={addModerator}><Plus/></button></div><div className="mods">{mods.map(m=><div key={m}><span><UserRound/>{m}</span><button onClick={()=>removeModerator(m)}><X/></button></div>)}</div></>}<p className="security-note"><ShieldCheck/>Доступ владельца: {OWNER_EMAIL}</p></>}
</section></div>}{toast&&<div className="toast"><Check/>{toast}</div>}</main>}
