import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {onAuthStateChanged,signInWithPopup,signOut,User} from "firebase/auth";
import {addDoc,arrayUnion,collection,deleteDoc,doc,getDoc,onSnapshot,orderBy,query,serverTimestamp,setDoc,updateDoc,where} from "firebase/firestore";
import {Bell,BriefcaseBusiness,Camera,Check,CircleUserRound,Download,Hammer,Languages,LocateFixed,MapPin,MessageCircle,Pencil,Plus,Search,Send,ShieldCheck,Trash2,UserRound,Users,Volume2,Wrench,X} from "lucide-react";
import MapPanel,{MapOrder} from "./MapPanel";
import {auth,db,googleProvider,OWNER_EMAIL} from "./firebase";

type Lang="ru"|"lv"|"en"|"uk"; type Role="customer"|"master";
type Profile={displayName:string;phone:string;bio:string;services:string;city:string;role:Role;avatar?:string;email?:string};
type Order={id:string;service:string;description:string;price:string;city:string;district:string;date:string;photo?:string;lat:number;lng:number;customerId:string;customerName:string;status:string;createdAt?:unknown};
type Chat={id:string;orderId:string;orderTitle:string;participants:string[];customerId:string;masterId:string;updatedAt?:unknown};
type Message={id:string;text:string;senderId:string;senderName:string;createdAt?:{toDate?:()=>Date}};
type Modal="login"|"order"|"profile"|"admin"|"chats"|null;
const ui={ru:{map:"Карта",orders:"Заявки",masters:"Мастера",search:"Что нужно сделать?",newOrder:"Создать заявку",roleC:"Я заказчик",roleM:"Я исполнитель",headline:"Найдите мастера рядом",sub:"Разместите задачу — исполнители предложат цену",login:"Войти через Google",profile:"Профиль",chats:"Чаты",near:"Заявки рядом",respond:"Написать заказчику",myOrders:"Мои объявления"},lv:{map:"Karte",orders:"Pasūtījumi",masters:"Meistari",search:"Kas jāizdara?",newOrder:"Izveidot pasūtījumu",roleC:"Esmu klients",roleM:"Esmu meistars",headline:"Atrodiet meistaru tuvumā",sub:"Publicējiet darbu — meistari piedāvās cenu",login:"Turpināt ar Google",profile:"Profils",chats:"Čati",near:"Pasūtījumi tuvumā",respond:"Rakstīt klientam",myOrders:"Mani sludinājumi"},en:{map:"Map",orders:"Requests",masters:"Pros",search:"What needs doing?",newOrder:"Post a request",roleC:"I'm a customer",roleM:"I'm a professional",headline:"Find a pro nearby",sub:"Post a task and receive offers",login:"Continue with Google",profile:"Profile",chats:"Chats",near:"Requests nearby",respond:"Message customer",myOrders:"My listings"},uk:{map:"Карта",orders:"Заявки",masters:"Майстри",search:"Що потрібно зробити?",newOrder:"Створити заявку",roleC:"Я замовник",roleM:"Я виконавець",headline:"Знайдіть майстра поруч",sub:"Опублікуйте завдання та отримайте пропозиції",login:"Увійти через Google",profile:"Профіль",chats:"Чати",near:"Заявки поруч",respond:"Написати замовнику",myOrders:"Мої оголошення"}};
const services=["Сантехник","Плиточник","Электрик","Сборка мебели","Маляр","Уборка","Перевозка","Ремонт техники"];
const fallback:Order[]=[{id:"demo1",service:"Установить смеситель",description:"Нужно заменить старый смеситель",price:"€35–50",city:"Rīga",district:"Purvciems",date:"Сегодня",lat:56.957,lng:24.18,customerId:"demo",customerName:"Anna",status:"open"},{id:"demo2",service:"Собрать шкаф IKEA",description:"Шкаф PAX, 2 секции",price:"€55–75",city:"Rīga",district:"Centrs",date:"Завтра",lat:56.952,lng:24.112,customerId:"demo",customerName:"Jānis",status:"open"},{id:"demo3",service:"Положить плитку 12 м²",description:"Ванная комната",price:"€240–320",city:"Rīga",district:"Imanta",date:"На неделе",lat:56.956,lng:24.01,customerId:"demo",customerName:"Maksims",status:"open"}];
function compressImage(file:File,max=900,quality=.72):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d")!.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",quality))};img.src=String(reader.result)};reader.readAsDataURL(file)})}
function coordsNear(center:[number,number]){return {lat:center[0]+(Math.random()-.5)*.018,lng:center[1]+(Math.random()-.5)*.028}}

export default function App(){
 const[lang,setLang]=useState<Lang>("ru"),[role,setRole]=useState<Role>("customer"),[user,setUser]=useState<User|null>(null),[profile,setProfile]=useState<Profile|null>(null),[modal,setModal]=useState<Modal>(null),[queryText,setQueryText]=useState(""),[toast,setToast]=useState(""),[busy,setBusy]=useState(false),[orders,setOrders]=useState<Order[]>([]),[editing,setEditing]=useState<Order|null>(null),[orderPhoto,setOrderPhoto]=useState(""),[avatar,setAvatar]=useState(""),[center,setCenter]=useState<[number,number]>([56.9496,24.1052]),[geoStatus,setGeoStatus]=useState("Rīga, Centrs"),[isModerator,setIsModerator]=useState(false),[modEmail,setModEmail]=useState(""),[chats,setChats]=useState<Chat[]>([]),[activeChat,setActiveChat]=useState<Chat|null>(null),[messages,setMessages]=useState<Message[]>([]),[message,setMessage]=useState("");
 const selectedCard=useRef<HTMLDivElement|null>(null),t=ui[lang],isOwner=user?.email?.toLowerCase()===OWNER_EMAIL,canModerate=isOwner||isModerator;
 const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),2600)};
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);setProfile(null);setIsModerator(false);if(!u)return;const ref=doc(db,"users",u.uid),snap=await getDoc(ref);const base:Profile={displayName:u.displayName||"",phone:"",bio:"",services:"",city:"Rīga",role:"customer",avatar:u.photoURL||"",email:u.email||""};if(snap.exists())setProfile({...base,...snap.data()} as Profile);else{await setDoc(ref,{...base,createdAt:serverTimestamp()});setProfile(base)}if(u.email)setIsModerator((await getDoc(doc(db,"moderators",u.email.toLowerCase()))).exists())}),[]);
 useEffect(()=>{const q=query(collection(db,"orders"),orderBy("createdAt","desc"));return onSnapshot(q,s=>setOrders(s.docs.map(d=>({id:d.id,...d.data()} as Order))),()=>setOrders([]))},[]);
 useEffect(()=>{if(!user){setChats([]);return}const q=query(collection(db,"chats"),where("participants","array-contains",user.uid));return onSnapshot(q,s=>setChats(s.docs.map(d=>({id:d.id,...d.data()} as Chat))))},[user]);
 useEffect(()=>{if(!activeChat){setMessages([]);return}const q=query(collection(db,"chats",activeChat.id,"messages"),orderBy("createdAt","asc"));return onSnapshot(q,s=>setMessages(s.docs.map(d=>({id:d.id,...d.data()} as Message))))},[activeChat]);
 const visible=useMemo(()=>{const q=queryText.toLowerCase();return (orders.length?orders:fallback).filter(o=>!q||`${o.service} ${o.description} ${o.district}`.toLowerCase().includes(q))},[orders,queryText]);
 const myOrders=orders.filter(o=>o.customerId===user?.uid);
 const login=async()=>{try{setBusy(true);await signInWithPopup(auth,googleProvider);setModal(null);notify("Вход выполнен")}catch(e){console.error(e);notify("Не удалось войти")}finally{setBusy(false)}};
 const locate=()=>{if(!navigator.geolocation)return notify("Геолокация недоступна");setGeoStatus("Определяем…");navigator.geolocation.getCurrentPosition(p=>{setCenter([p.coords.latitude,p.coords.longitude]);setGeoStatus("Ваше местоположение");notify("Карта перемещена к вам")},()=>{setGeoStatus("Доступ к геолокации закрыт");notify("Разрешите геолокацию в браузере")},{enableHighAccuracy:true,timeout:10000})};
 const pickImage=async(e:React.ChangeEvent<HTMLInputElement>,kind:"avatar"|"order")=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8_000_000)return notify("Фото должно быть меньше 8 МБ");const data=await compressImage(f,kind==="avatar"?420:1000,kind==="avatar"?.76:.7);kind==="avatar"?setAvatar(data):setOrderPhoto(data)};
 const saveProfile=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!user)return;const f=new FormData(e.currentTarget),data:Profile={displayName:String(f.get("displayName")||""),phone:String(f.get("phone")||""),bio:String(f.get("bio")||""),services:String(f.get("services")||""),city:String(f.get("city")||"Rīga"),role:String(f.get("role")||"customer") as Role,avatar:avatar||profile?.avatar||user.photoURL||"",email:user.email||""};try{setBusy(true);await setDoc(doc(db,"users",user.uid),{...data,updatedAt:serverTimestamp()},{merge:true});setProfile(data);setRole(data.role);setModal(null);notify("Профиль сохранён")}catch(e){console.error(e);notify("Ошибка сохранения профиля")}finally{setBusy(false)}};
 const openOrder=(o?:Order)=>{if(!user){setModal("login");return}setEditing(o||null);setOrderPhoto(o?.photo||"");setModal("order")};
 const saveOrder=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!user)return;const f=new FormData(e.currentTarget),c=editing?{lat:editing.lat,lng:editing.lng}:coordsNear(center),data={service:String(f.get("service")),description:String(f.get("description")),price:String(f.get("price")||"Цена договорная"),city:String(f.get("city")),district:String(f.get("district")),date:String(f.get("date")),photo:orderPhoto,lat:c.lat,lng:c.lng,customerId:user.uid,customerName:profile?.displayName||user.displayName||"Заказчик",status:"open",updatedAt:serverTimestamp()};try{setBusy(true);if(editing)await updateDoc(doc(db,"orders",editing.id),data);else await addDoc(collection(db,"orders"),{...data,createdAt:serverTimestamp()});setModal(null);setEditing(null);notify(editing?"Объявление обновлено":"Объявление опубликовано")}catch(err){console.error(err);notify("Не удалось сохранить объявление")}finally{setBusy(false)}};
 const removeOrder=async(o:Order)=>{if(!user||o.customerId!==user.uid)return;if(!confirm("Удалить объявление?"))return;await deleteDoc(doc(db,"orders",o.id));notify("Объявление удалено")};
 const startChat=async(o:Order)=>{if(!user){setModal("login");return}if(o.customerId===user.uid)return notify("Это ваше объявление");const id=`${o.id}_${o.customerId}_${user.uid}`,ref=doc(db,"chats",id);await setDoc(ref,{orderId:o.id,orderTitle:o.service,participants:[o.customerId,user.uid],customerId:o.customerId,masterId:user.uid,updatedAt:serverTimestamp()},{merge:true});const chat={id,orderId:o.id,orderTitle:o.service,participants:[o.customerId,user.uid],customerId:o.customerId,masterId:user.uid};setActiveChat(chat);setModal("chats")};
 const sendMessage=async(e:FormEvent)=>{e.preventDefault();if(!user||!activeChat||!message.trim())return;const text=message.trim();setMessage("");await addDoc(collection(db,"chats",activeChat.id,"messages"),{text,senderId:user.uid,senderName:profile?.displayName||user.displayName||"Пользователь",createdAt:serverTimestamp()});await updateDoc(doc(db,"chats",activeChat.id),{lastMessage:text,updatedAt:serverTimestamp()})};
 const addModerator=async()=>{const email=modEmail.trim().toLowerCase();if(!isOwner||!email.includes("@"))return;await setDoc(doc(db,"moderators",email),{email,addedAt:serverTimestamp(),addedBy:user?.email});setModEmail("");notify("Модератор добавлен")};

 return <main className="app-shell"><header className="topbar"><button className="brand"><span className="brand-mark"><Hammer/></span><span>MURDILI<b>MAX</b></span></button><nav><button className="active"><MapPin/>{t.map}</button><button onClick={()=>selectedCard.current?.scrollIntoView({behavior:"smooth"})}><BriefcaseBusiness/>{t.orders}</button><button><Users/>{t.masters}</button></nav><div className="top-actions"><button className="icon-button" onClick={()=>notify("Звуки включены")}><Volume2/></button><div className="language"><Languages/><select value={lang} onChange={e=>setLang(e.target.value as Lang)}>{["ru","lv","en","uk"].map(x=><option key={x} value={x}>{x==="uk"?"UA":x.toUpperCase()}</option>)}</select></div>{user&&<button className="icon-button" title={t.chats} onClick={()=>setModal("chats")}><MessageCircle/></button>}<button className="login-button" onClick={()=>user?setModal("profile"):setModal("login")}><CircleUserRound/><span>{user?profile?.displayName||t.profile:t.login}</span></button></div></header>
 <section className="command-panel"><div className="role-switch"><button className={role==="customer"?"active":""} onClick={()=>setRole("customer")}><UserRound/>{t.roleC}</button><button className={role==="master"?"active":""} onClick={()=>setRole("master")}><Wrench/>{t.roleM}</button></div><div className="headline"><div><p className="eyebrow">MURDILIMAX · LATVIJA</p><h1>{t.headline}</h1><p>{t.sub}</p></div><button className="primary" onClick={()=>openOrder()}><Plus/>{t.newOrder}</button></div><div className="search-row"><label className="searchbox"><Search/><input value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder={t.search}/></label><button className="location"><MapPin/><span>{geoStatus}</span></button><button className="locate" onClick={locate}><LocateFixed/></button></div><div className="service-strip">{services.map(s=><button key={s} onClick={()=>setQueryText(s)}>{s}</button>)}</div></section>
 <section className="workspace"><div className="map-card"><div className="map-toolbar"><div><strong>{t.near}</strong><span>{geoStatus} · {visible.length}</span></div><button onClick={locate}><LocateFixed/>Где я</button></div><MapPanel center={center} orders={visible.map(o=>({id:o.id,service:o.service,price:o.price,district:o.district,lat:o.lat,lng:o.lng} as MapOrder))} onSelect={id=>document.getElementById(`order-${id}`)?.scrollIntoView({behavior:"smooth",block:"center"})}/></div><aside className="feed" ref={selectedCard}><div className="section-title"><div><h2>{role==="customer"?t.myOrders:t.near}</h2><p>{user?"Данные обновляются автоматически":"Войдите, чтобы публиковать и писать"}</p></div><button><Bell/></button></div>{(role==="customer"&&user?myOrders:visible).map(o=><article id={`order-${o.id}`} className="job-card rich" key={o.id}>{o.photo&&<img className="order-thumb" src={o.photo} alt=""/>}<div className="job-top"><div><h3>{o.service}</h3><p><MapPin/>{o.district}, {o.city} · {o.date}</p></div><strong>{o.price}</strong></div><p className="order-description">{o.description}</p>{o.customerId===user?.uid?<div className="card-actions"><button onClick={()=>openOrder(o)}><Pencil/>Редактировать</button><button className="danger" onClick={()=>removeOrder(o)}><Trash2/>Удалить</button></div>:<button className="chat-cta" onClick={()=>startChat(o)}>{t.respond}<MessageCircle/></button>}</article>)}{role==="customer"&&user&&myOrders.length===0&&<div className="empty"><BriefcaseBusiness/><b>Пока нет объявлений</b><button className="primary" onClick={()=>openOrder()}>Создать первое</button></div>}</aside></section>
 <footer><span>© 2026 MURDILIMAX</span><button><Download/>Установить приложение</button>{user&&<button onClick={()=>setModal("profile")}><UserRound/>{t.profile}</button>}{canModerate&&<button onClick={()=>setModal("admin")}><ShieldCheck/>Админ-панель</button>}</footer>
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><section className={`modal ${modal==="chats"?"chat-modal":""}`} onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>
 {modal==="login"&&<><div className="modal-icon"><CircleUserRound/></div><h2>{t.login}</h2><p>Один аккаунт для заказчика и исполнителя.</p><button className="google" disabled={busy} onClick={login}><b>G</b>{busy?"Подключение…":t.login}</button></>}
 {modal==="profile"&&user&&<form onSubmit={saveProfile}><div className="profile-head"><label className="avatar-editor">{avatar||profile?.avatar?<img src={avatar||profile?.avatar}/>:<UserRound/>}<span><Camera/></span><input type="file" accept="image/*" onChange={e=>pickImage(e,"avatar")}/></label><div><h2>{t.profile}</h2><p>{user.email}</p></div></div><div className="form-grid"><label>Имя<input name="displayName" required defaultValue={profile?.displayName}/></label><label>Телефон<input name="phone" defaultValue={profile?.phone}/></label><label>Город<input name="city" defaultValue={profile?.city||"Rīga"}/></label><label>Роль<select name="role" defaultValue={profile?.role||role}><option value="customer">Заказчик</option><option value="master">Исполнитель</option></select></label><label className="wide">О себе<textarea name="bio" defaultValue={profile?.bio} placeholder="Опыт, языки, график работы"/></label><label className="wide">Какие работы выполняете<textarea name="services" defaultValue={profile?.services} placeholder="Сантехника, мебель, электрика…"/></label></div><button className="primary wide-button" disabled={busy}><Check/>Сохранить профиль</button><button type="button" className="logout" onClick={()=>{signOut(auth);setModal(null)}}>Выйти из аккаунта</button></form>}
 {modal==="order"&&user&&<form onSubmit={saveOrder}><div className="modal-icon"><Plus/></div><h2>{editing?"Редактировать объявление":t.newOrder}</h2><label className="photo-picker">{orderPhoto?<img src={orderPhoto}/>:<><Camera/><span>Добавить фото работы</span></>}<input type="file" accept="image/*" onChange={e=>pickImage(e,"order")}/></label><div className="form-grid"><label>Услуга<input name="service" required defaultValue={editing?.service}/></label><label>Цена<input name="price" placeholder="Например, €40–60" defaultValue={editing?.price}/></label><label>Город<input name="city" required defaultValue={editing?.city||profile?.city||"Rīga"}/></label><label>Район<input name="district" required defaultValue={editing?.district||"Centrs"}/></label><label>Когда<input name="date" required defaultValue={editing?.date||"В ближайшее время"}/></label><label className="wide">Описание<textarea name="description" required defaultValue={editing?.description}/></label></div><button className="primary wide-button" disabled={busy}><Check/>{busy?"Сохраняем…":"Сохранить объявление"}</button></form>}
 {modal==="chats"&&user&&<div className="chat-layout"><aside><h2>{t.chats}</h2>{chats.map(c=><button className={activeChat?.id===c.id?"active":""} onClick={()=>setActiveChat(c)} key={c.id}><MessageCircle/><span><b>{c.orderTitle}</b><small>{c.id===activeChat?.id?"Открыт":"Переписка"}</small></span></button>)}{!chats.length&&<p>Пока нет чатов. Исполнитель может открыть чат из объявления.</p>}</aside><section>{activeChat?<><header><b>{activeChat.orderTitle}</b><span>Защищённый чат</span></header><div className="messages">{messages.map(m=><div className={m.senderId===user.uid?"mine":""} key={m.id}><b>{m.senderName}</b><p>{m.text}</p></div>)}</div><form className="message-form" onSubmit={sendMessage}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Напишите сообщение…"/><button><Send/></button></form></>:<div className="empty-chat"><MessageCircle/><p>Выберите чат слева</p></div>}</section></div>}
 {modal==="admin"&&canModerate&&<><div className="modal-icon"><ShieldCheck/></div><h2>Админ-панель</h2><p>{user?.email} · {isOwner?"владелец":"модератор"}</p>{isOwner&&<><h3>Добавить модератора</h3><div className="add-mod"><input value={modEmail} onChange={e=>setModEmail(e.target.value)} placeholder="moderator@gmail.com"/><button onClick={addModerator}><Plus/></button></div></>}<p className="security-note"><ShieldCheck/>Доступ владельца: {OWNER_EMAIL}</p></>}
 </section></div>}{toast&&<div className="toast"><Check/>{toast}</div>}</main>
}
