// NEXUS ALPHA — HD premium crypto bubble map. Focused visual product; no legacy MEXC/RAVE UI.
(function(){
  if(window.__nexusMarketMapLoaded)return;window.__nexusMarketMapLoaded=true;
  const MM={kind:'market',start:0,period:'24h',items:[],nodes:[],loading:false,updatedAt:0,total:0,resizeTimer:null};
  state.marketMap=MM;
  const ru=()=>state.lang==='ru';
  const tx=(a,b)=>ru()?a:b;
  const money=v=>{v=Number(v)||0;if(v>=1e12)return'$'+(v/1e12).toFixed(2)+'T';if(v>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(v>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(v>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toLocaleString(undefined,{maximumFractionDigits:2})};
  const price=v=>{v=Number(v)||0;if(!v)return'—';if(v>=1000)return'$'+v.toLocaleString(undefined,{maximumFractionDigits:2});if(v>=1)return'$'+v.toLocaleString(undefined,{maximumFractionDigits:4});if(v>=.01)return'$'+v.toFixed(5);return'$'+v.toPrecision(4)};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  document.body.classList.add('nexus-map-only');
  document.getElementById('radarModeSwitch')?.remove();
  document.getElementById('extremeWorkspace')?.remove();
  document.querySelectorAll('.mexc-panel,.extreme-panel,.radar-mode-switch').forEach(x=>x.remove());

  const shell=document.querySelector('main.shell');if(!shell)return;
  const map=document.createElement('section');map.id='nexusMarketMap';map.className='nexus-market-map';
  map.innerHTML=`<div class="nm-top"><div class="nm-kinds" id="nmKinds"><button class="active" data-kind="market">${tx('РЫНОК','MARKET')}</button><button data-kind="pump">PUMP.FUN</button><button data-kind="dex">DEX VETTED</button><button data-kind="precex">PRE-CEX</button></div><div class="nm-status"><i></i><span>LIVE</span></div></div>
  <div class="nm-ranks" id="nmRanks"></div>
  <div class="nm-heading"><div><small id="nmEyebrow">NEXUS MARKET MAP</small><h1 id="nmTitle">TOP #1–100</h1></div><div class="nm-meta" id="nmMeta">—</div></div>
  <div class="nm-stage" id="nmStage"><div class="nm-vignette"></div><div class="nm-bubbles" id="nmBubbles"></div><div class="nm-loading" id="nmLoading"><span></span>${tx('ЗАГРУЖАЕМ РЫНОК','LOADING MARKET')}</div><div class="nm-empty" id="nmEmpty"></div></div>
  <div class="nm-bottom"><div class="nm-periods" id="nmPeriods"><button data-period="1h">1H</button><button class="active" data-period="24h">24H</button><button data-period="7d">7D</button></div><div class="nm-legend"><span class="up"></span>UP <span class="flat"></span>FLAT <span class="down"></span>DOWN</div></div>
  <div class="nm-sheet" id="nmSheet"><button class="nm-sheet-close" id="nmSheetClose">×</button><div id="nmSheetBody"></div></div>`;
  shell.prepend(map);

  function buildRanks(){const box=document.getElementById('nmRanks');box.innerHTML=Array.from({length:10},(_,i)=>`<button data-start="${i*100}" class="${i===0?'active':''}">${i*100+1}–${i*100+100}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{MM.start=Number(b.dataset.start)||0;box.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));loadMap()})}
  buildRanks();
  document.querySelectorAll('#nmKinds button').forEach(b=>b.onclick=()=>{MM.kind=b.dataset.kind;document.querySelectorAll('#nmKinds button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('nmRanks').classList.toggle('hidden',MM.kind!=='market');loadMap()});
  document.querySelectorAll('#nmPeriods button').forEach(b=>b.onclick=()=>{MM.period=b.dataset.period;document.querySelectorAll('#nmPeriods button').forEach(x=>x.classList.toggle('active',x===b));render()});
  document.getElementById('nmSheetClose').onclick=()=>document.getElementById('nmSheet').classList.remove('show');

  function primaryLogo(c){const s=String(c.symbol||'').toLowerCase().replace(/[^a-z0-9]/g,'');return s?`https://assets.coincap.io/assets/icons/${s}@2x.png`:''}
  function fallbackLogo(c){return c.image||c.logo||(c.nameid?`https://c2.coinlore.com/img/25x25/${encodeURIComponent(c.nameid)}.png`:'')}
  function tokenToItem(tk,kind){const d=tk.dex||{},cap=Number(d.marketCap||d.fdv||tk.pump?.marketCapUsd||0)||0,liq=Number(d.liquidityUsd||0)||0;return{id:tk.mint,symbol:String(tk.symbol||'?').toUpperCase(),name:tk.name||tk.symbol||'Token',price:Number(d.priceUsd||0)||0,marketCap:cap||liq*2.5,volume24:Number(d.volumeH24||d.volumeH6||d.volumeH1||0)||0,change1h:Number(d.changeH1||d.changeM5||0)||0,change24h:Number(d.changeH24||d.change24h||d.changeH1||0)||0,change7d:Number(d.changeH24||d.change24h||0)||0,image:tk.image||tk.logo||'',liquidity:liq,raw:tk,kind}}
  function change(c){return Number(MM.period==='1h'?c.change1h:MM.period==='7d'?c.change7d:c.change24h)||0}
  function showLoad(v){document.getElementById('nmLoading')?.classList.toggle('show',v)}
  async function loadMap(){if(MM.loading)return;MM.loading=true;showLoad(true);document.getElementById('nmEmpty').textContent='';try{
    if(MM.kind==='market'){const r=await fetch(`${API_BASE}/api/market-map?start=${MM.start}&limit=100`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();MM.items=d.coins||[];MM.total=d.total||0;MM.updatedAt=d.generatedAt||Date.now()}
    else if(MM.kind==='pump'){const r=await fetch(`${API_BASE}/api/radar-v3?limit=600&maxAgeHours=24`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();MM.items=(d.tokens||[]).filter(t=>t.pump||String(t.source||'').toLowerCase().includes('pump')).map(t=>tokenToItem(t,'pump')).sort((a,b)=>b.marketCap-a.marketCap).slice(0,180);MM.updatedAt=d.generatedAt||Date.now()}
    else{const r=await fetch(`${API_BASE}/api/vetted?limit=400`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();let rows=d.tokens||[];if(MM.kind==='precex')rows=rows.filter(t=>t.vetted?.cex?.preCexCandidate||t.vetted?.cex?.projectClaimDetected);MM.items=rows.map(t=>tokenToItem(t,MM.kind)).sort((a,b)=>b.marketCap-a.marketCap).slice(0,180);MM.updatedAt=d.generatedAt||Date.now()}
    updateHead();render();
  }catch(e){MM.items=[];render();document.getElementById('nmEmpty').textContent=tx('Источник временно недоступен','Source temporarily unavailable')+' · '+e.message}finally{MM.loading=false;showLoad(false)}}
  function updateHead(){const title=document.getElementById('nmTitle'),meta=document.getElementById('nmMeta'),eye=document.getElementById('nmEyebrow');if(MM.kind==='market'){title.textContent=`TOP #${MM.start+1}–${MM.start+100}`;eye.textContent='NEXUS MARKET MAP'}else if(MM.kind==='pump'){title.textContent='PUMP.FUN · LIVE';eye.textContent=tx('НОВЫЕ ТОКЕНЫ','NEW TOKENS')}else if(MM.kind==='dex'){title.textContent='DEX VETTED';eye.textContent=tx('ПРОВЕРЕННЫЕ DEX-АКТИВЫ','VETTED DEX ASSETS')}else{title.textContent='PRE-CEX';eye.textContent=tx('ЕЩЁ НЕ НА КРУПНЫХ CEX','NOT ON MAJOR CEX')}meta.textContent=`${MM.items.length} ${tx('активов','assets')} · ${new Date(MM.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`}

  function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0)/4294967295}
  function radii(items,w,h){if(!items.length)return[];const vals=items.map(x=>Math.log10(Math.max(1,x.marketCap||x.liquidity||x.volume24||1))),lo=Math.min(...vals),hi=Math.max(...vals),mobile=w<700;let rs=vals.map(v=>{const n=hi>lo?(v-lo)/(hi-lo):.5;return(mobile?8:10)+(mobile?52:72)*Math.pow(Math.max(0,Math.min(1,n)),1.62)});const area=rs.reduce((a,r)=>a+Math.PI*r*r,0),target=w*h*(mobile?.68:.72),scale=Math.min(1.1,Math.sqrt(target/Math.max(1,area)));return rs.map(r=>Math.max(mobile?7:9,r*scale))}
  function layout(items,w,h){if(!items.length)return[];const rs=radii(items,w,h),cx=w/2,cy=h/2,golden=2.399963229728653,nodes=items.map((item,i)=>{const a=i*golden+hash(item.id||item.symbol)*4,rad=Math.sqrt(i+1)*Math.min(w,h)*.022;return{item,r:rs[i],x:cx+Math.cos(a)*rad,y:cy+Math.sin(a)*rad,vx:0,vy:0}}).sort((a,b)=>b.r-a.r);for(let k=0;k<310;k++){for(let i=0;i<nodes.length;i++){const a=nodes[i];a.vx+=(cx-a.x)*.00135;a.vy+=(cy-a.y)*.0011;for(let j=i+1;j<nodes.length;j++){const b=nodes[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01,min=a.r+b.r+.35;if(d<min){const q=(min-d)/d*.48,px=dx*q,py=dy*q;a.vx-=px;b.vx+=px;a.vy-=py;b.vy+=py}}}for(const n of nodes){n.vx*=.60;n.vy*=.60;n.x+=n.vx;n.y+=n.vy;n.x=Math.max(n.r+.5,Math.min(w-n.r-.5,n.x));n.y=Math.max(n.r+.5,Math.min(h-n.r-.5,n.y))}}return nodes}
  function tone(ch){const abs=Math.abs(ch);if(abs<.35)return{cls:'flat',h:210,s:14,l:19,edge:'rgba(150,166,184,.24)',glow:'rgba(130,155,185,.05)',pct:'#c0cad3'};if(ch>0){const k=Math.min(1,(abs-.35)/12),s=36+k*34,l=22+k*7;return{cls:abs>=5?'hot up':'up',h:150,s,l,edge:`rgba(64,245,145,${.36+k*.48})`,glow:`rgba(40,255,128,${.06+k*.32})`,pct:abs>=3?'#70ffac':'#b8e8cb'}}const k=Math.min(1,(abs-.35)/12),s=34+k*38,l=22+k*7;return{cls:abs>=5?'hot down':'down',h:350,s,l,edge:`rgba(255,77,105,${.34+k*.5})`,glow:`rgba(255,44,77,${.05+k*.3})`,pct:abs>=3?'#ff8295':'#e9bac1'}}
  function render(){const stage=document.getElementById('nmStage'),box=document.getElementById('nmBubbles');if(!stage||!box)return;const w=Math.max(300,stage.clientWidth),h=Math.max(520,stage.clientHeight);MM.nodes=layout(MM.items,w,h);box.replaceChildren();if(!MM.items.length){document.getElementById('nmEmpty').textContent=tx('Сейчас здесь нет данных','No data here right now');return}else document.getElementById('nmEmpty').textContent='';const frag=document.createDocumentFragment();for(const n of MM.nodes){const c=n.item,ch=change(c),t=tone(ch),d=n.r*2,b=document.createElement('button');b.className=`nm-bubble ${t.cls}`;b.type='button';b.style.cssText=`width:${d}px;height:${d}px;left:${n.x-n.r}px;top:${n.y-n.r}px;--h:${t.h};--s:${t.s}%;--l:${t.l}%;--edge:${t.edge};--glow:${t.glow};--pct:${t.pct};`;const r=n.r,hi=primaryLogo(c),lo=fallbackLogo(c),logo=hi||lo;let inner='<i class="nm-shine"></i>';if(logo&&r>=10)inner+=`<span class="nm-logo"><img src="${esc(logo)}" data-fallback="${esc(lo)}" alt="" loading="lazy"></span>`;if(r>=18)inner+=`<strong>${esc(c.symbol.slice(0,r<26?5:8))}</strong>`;if(r>=25)inner+=`<span class="nm-change">${ch>=0?'+':''}${ch.toFixed(Math.abs(ch)>=100?0:1)}%</span>`;b.innerHTML=inner;b.querySelector('img')?.addEventListener('error',function(){const f=this.dataset.fallback;if(f&&this.src!==f){this.src=f;this.dataset.fallback=''}else this.closest('.nm-logo')?.remove()});b.setAttribute('aria-label',`${c.name} ${ch>=0?'+':''}${ch.toFixed(2)}%`);b.onclick=()=>openItem(c);frag.appendChild(b)}box.appendChild(frag)}
  function openItem(c){if(c.raw&&typeof renderDetail==='function'){renderDetail(c.raw);return}const sheet=document.getElementById('nmSheet'),body=document.getElementById('nmSheetBody'),ch=change(c),hi=primaryLogo(c),lo=fallbackLogo(c);if(!sheet||!body)return;body.innerHTML=`<div class="nm-coin-head"><span class="nm-sheet-logo">${hi||lo?`<img src="${esc(hi||lo)}" data-fallback="${esc(lo)}" alt="">`:''}</span><div><small>#${c.rank||'—'}</small><h2>${esc(c.name)}</h2><b>${esc(c.symbol)}</b></div><strong class="${ch>=0?'pos':'neg'}">${ch>=0?'+':''}${ch.toFixed(2)}%</strong></div><div class="nm-info"><div><span>${tx('Цена','Price')}</span><b>${price(c.price)}</b></div><div><span>${tx('Капитализация','Market cap')}</span><b>${money(c.marketCap)}</b></div><div><span>${tx('Объём 24ч','24h volume')}</span><b>${money(c.volume24)}</b></div><div><span>1H</span><b>${Number(c.change1h)>=0?'+':''}${Number(c.change1h||0).toFixed(2)}%</b></div><div><span>24H</span><b>${Number(c.change24h)>=0?'+':''}${Number(c.change24h||0).toFixed(2)}%</b></div><div><span>7D</span><b>${Number(c.change7d)>=0?'+':''}${Number(c.change7d||0).toFixed(2)}%</b></div></div>`;body.querySelector('img')?.addEventListener('error',function(){const f=this.dataset.fallback;if(f&&this.src!==f){this.src=f;this.dataset.fallback=''}else this.remove()});sheet.classList.add('show')}

  const style=document.createElement('style');style.textContent=`
  .nexus-map-only .hero-strip,.nexus-map-only .market-regime-bar,.nexus-map-only .stat-grid,.nexus-map-only .control-deck,.nexus-map-only .workspace,.nexus-map-only .seo-about,.nexus-map-only .truth-bar{display:none!important}
  .nexus-map-only .shell{max-width:none!important;padding:0!important}.nexus-map-only{background:#020305}.nexus-market-map{width:100%;min-height:calc(100dvh - 72px);padding:9px 10px 12px;box-sizing:border-box;color:#f8fafc;background:radial-gradient(ellipse at 50% -5%,rgba(22,35,42,.35),transparent 40%),#020305}
  .nm-top{display:flex;align-items:center;justify-content:space-between;gap:8px;max-width:1600px;margin:0 auto 7px}.nm-kinds,.nm-ranks,.nm-periods{display:flex;gap:5px;overflow:auto;scrollbar-width:none}.nm-kinds::-webkit-scrollbar,.nm-ranks::-webkit-scrollbar{display:none}.nm-kinds button,.nm-ranks button,.nm-periods button{border:1px solid rgba(255,255,255,.075);background:linear-gradient(180deg,#0b0e13,#07090d);color:#7e8995;border-radius:9px;padding:7px 11px;font:800 9px/1 system-ui;letter-spacing:.055em;white-space:nowrap;box-shadow:inset 0 1px rgba(255,255,255,.025)}.nm-kinds button.active{color:#f5fff9;border-color:rgba(79,228,165,.3);background:linear-gradient(180deg,rgba(28,77,60,.46),rgba(9,25,20,.75));box-shadow:inset 0 1px rgba(140,255,207,.08),0 0 18px rgba(63,255,171,.045)}.nm-status{display:flex;align-items:center;gap:6px;color:#5be9ad;font:900 8px/1 system-ui;letter-spacing:.12em}.nm-status i{width:6px;height:6px;border-radius:50%;background:#55efad;box-shadow:0 0 11px rgba(85,239,173,.7)}
  .nm-ranks{max-width:1600px;margin:0 auto 4px}.nm-ranks.hidden{display:none}.nm-ranks button{padding:5px 9px;font-size:8px;border-radius:7px}.nm-ranks button.active{color:#dffaff;border-color:rgba(89,219,255,.25);background:rgba(50,148,177,.09)}.nm-heading{max-width:1600px;margin:0 auto 3px;display:flex;align-items:end;justify-content:space-between;padding:0 2px}.nm-heading small{font:900 7px/1 system-ui;letter-spacing:.23em;color:#5ce4ff}.nm-heading h1{font:850 17px/.95 system-ui;margin:5px 0 0;letter-spacing:-.02em}.nm-meta{font:700 8px/1 system-ui;color:#5e6974;white-space:nowrap}
  .nm-stage{position:relative;max-width:1600px;margin:0 auto;height:calc(100dvh - 220px);min-height:600px;max-height:1080px;overflow:hidden;background:#010203;border:1px solid rgba(255,255,255,.035);box-shadow:inset 0 0 120px rgba(0,0,0,.9)}.nm-vignette{position:absolute;inset:0;pointer-events:none;z-index:2;background:radial-gradient(ellipse at center,transparent 54%,rgba(0,0,0,.22) 82%,rgba(0,0,0,.62) 100%)}.nm-bubbles{position:absolute;inset:0;z-index:1}
  .nm-bubble{position:absolute;border:0;border-radius:50%;padding:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px;isolation:isolate;overflow:visible;cursor:pointer;color:#fff;background:radial-gradient(circle at 36% 27%,hsla(var(--h),var(--s),55%,.17),transparent 29%),radial-gradient(circle at 50% 56%,hsl(var(--h) var(--s) calc(var(--l) + 3%)),hsl(var(--h) var(--s) calc(var(--l) - 4%)) 76%,#080a0e 100%);box-shadow:0 0 0 .75px var(--edge),inset 0 0 0 1px rgba(255,255,255,.035),inset 0 -8px 18px rgba(0,0,0,.25),0 0 9px var(--glow);transition:transform .13s ease,filter .13s ease;transform:translateZ(0);-webkit-font-smoothing:antialiased}.nm-bubble::before{content:"";position:absolute;inset:1.5px;border-radius:50%;border:1px solid rgba(255,255,255,.035);box-shadow:inset 0 1px 1px rgba(255,255,255,.065);pointer-events:none}.nm-bubble::after{content:"";position:absolute;inset:-2px;border-radius:50%;box-shadow:0 0 0 .45px var(--edge);opacity:.42;pointer-events:none}.nm-bubble.hot{box-shadow:0 0 0 1px var(--edge),inset 0 0 0 1px rgba(255,255,255,.06),inset 0 -10px 22px rgba(0,0,0,.24),0 0 18px var(--glow),0 0 34px var(--glow)}.nm-bubble:active{transform:scale(.94)}.nm-bubble:hover{filter:brightness(1.13);z-index:8}.nm-shine{position:absolute;z-index:0;width:62%;height:34%;top:5%;left:12%;border-radius:50%;background:radial-gradient(ellipse,rgba(255,255,255,.10),rgba(255,255,255,0) 72%);transform:rotate(-24deg);pointer-events:none}.nm-logo{z-index:2;display:grid;place-items:center;width:31%;height:31%;min-width:9px;min-height:9px;max-width:34px;max-height:34px;border-radius:50%;overflow:hidden;background:rgba(255,255,255,.93);box-shadow:0 1px 3px rgba(0,0,0,.65),0 0 0 .5px rgba(255,255,255,.28);margin-bottom:1px}.nm-logo img{display:block;width:100%;height:100%;object-fit:cover;image-rendering:auto}.nm-bubble strong{z-index:2;display:block;max-width:84%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:900 clamp(6px,1.4vw,14px)/1 system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:-.02em;text-shadow:0 1px 3px #000,0 0 5px rgba(0,0,0,.85)}.nm-change{z-index:2;color:var(--pct);font:850 clamp(6px,1.12vw,11px)/1 system-ui;letter-spacing:-.02em;text-shadow:0 1px 3px #000}
  .nm-loading{position:absolute;inset:0;display:none;align-items:center;justify-content:center;gap:9px;background:rgba(2,3,5,.72);z-index:12;font:800 9px/1 system-ui;letter-spacing:.12em;color:#8c99a5;backdrop-filter:blur(3px)}.nm-loading.show{display:flex}.nm-loading span{width:13px;height:13px;border:2px solid rgba(93,228,255,.15);border-top-color:#5de4ff;border-radius:50%;animation:nmspin .7s linear infinite}@keyframes nmspin{to{transform:rotate(360deg)}}.nm-empty{position:absolute;z-index:11;left:50%;top:50%;transform:translate(-50%,-50%);font-size:10px;color:#66717d;text-align:center;pointer-events:none}
  .nm-bottom{max-width:1600px;margin:7px auto 0;display:flex;align-items:center;justify-content:space-between;gap:10px}.nm-periods button{min-width:58px;padding:8px 12px;font-size:10px}.nm-periods button.active{color:#fff;background:linear-gradient(180deg,#ea5c63,#d8444c);border-color:#f06a71;box-shadow:0 4px 16px rgba(226,67,78,.16),inset 0 1px rgba(255,255,255,.13)}.nm-legend{font:800 7px/1 system-ui;color:#65717e;display:flex;align-items:center;gap:5px}.nm-legend span{width:7px;height:7px;border-radius:50%}.nm-legend .up{background:#4beaa5;box-shadow:0 0 7px rgba(75,234,165,.65)}.nm-legend .flat{background:#78838e}.nm-legend .down{background:#ef566e;box-shadow:0 0 7px rgba(239,86,110,.6)}
  .nm-sheet{position:fixed;z-index:100;left:50%;bottom:14px;width:min(560px,calc(100% - 20px));transform:translate(-50%,125%);opacity:0;border:1px solid rgba(255,255,255,.09);border-radius:18px;background:rgba(7,10,14,.97);box-shadow:0 18px 70px rgba(0,0,0,.68);padding:18px;box-sizing:border-box;transition:.22s ease;backdrop-filter:blur(24px)}.nm-sheet.show{transform:translate(-50%,0);opacity:1}.nm-sheet-close{position:absolute;right:10px;top:8px;background:none;border:0;color:#8996a3;font-size:25px}.nm-coin-head{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding-right:24px}.nm-sheet-logo{width:44px;height:44px;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:#111820}.nm-sheet-logo img{width:100%;height:100%;object-fit:cover}.nm-coin-head small,.nm-coin-head b{display:block;color:#768493;font-size:9px}.nm-coin-head h2{margin:2px 0;font-size:19px}.nm-coin-head>strong{font-size:18px}.nm-coin-head .pos{color:#62efb4}.nm-coin-head .neg{color:#ff7185}.nm-info{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:15px}.nm-info>div{border:1px solid rgba(255,255,255,.065);background:rgba(255,255,255,.016);padding:9px;border-radius:10px}.nm-info span{display:block;font-size:7px;color:#6e7a87;text-transform:uppercase}.nm-info b{display:block;margin-top:4px;font-size:11px}
  @media(max-width:760px){.nexus-map-only .topbar{padding:10px 12px}.nexus-map-only .brand-copy small,.nexus-map-only .latency-chip{display:none}.nexus-market-map{padding:7px 5px 9px}.nm-top{margin-bottom:4px}.nm-kinds button{padding:7px 9px;font-size:8px}.nm-ranks{margin-bottom:2px}.nm-ranks button{padding:5px 8px}.nm-heading{padding:0 1px}.nm-heading h1{font-size:15px}.nm-heading small{font-size:7px}.nm-stage{height:calc(100dvh - 208px);min-height:540px;border-left:0;border-right:0}.nm-logo{max-width:29px;max-height:29px}.nm-bubble strong{font-size:8px}.nm-change{font-size:7px}.nm-bottom{margin-top:5px}.nm-periods button{min-width:52px;padding:8px 10px}.nm-legend{display:none}.nm-info{grid-template-columns:repeat(2,1fr)}}
  `;document.head.appendChild(style);
  window.addEventListener('resize',()=>{clearTimeout(MM.resizeTimer);MM.resizeTimer=setTimeout(render,130)});
  loadMap();setInterval(()=>{if(document.visibilityState==='visible')loadMap()},60000);
})();
