// NEXUS ALPHA clarity layer: explain VETTED DEX and show only RAVE-type MEXC extreme structures.
(function(){
 const reasonRu={mexc_only_no_major_cex:'нет на крупных CEX',young_or_mid_age_market:'не заезженный рынок',near_90d_floor:'цена рядом с 90-дневным полом',tight_7d_base:'узкая база 7д',compressed_30d_base:'сжатая база 30д',volume_ignition:'объём просыпается',volume_before_price:'объём растёт раньше цены',hourly_compression:'часовые свечи сжаты',bid_depth_advantage:'bid сильнее ask',explosive_but_real_book:'стакан тонкий, но реальный',high_turnover_vs_depth:'оборот большой относительно стакана'};
 function pct(v){return v==null?'—':Number(v).toFixed(0)+'%'}
 function ensureModeHelp(){const sw=document.getElementById('radarModeSwitch');if(!sw||document.getElementById('focusedModeHelp'))return;sw.insertAdjacentHTML('afterend','<section id="focusedModeHelp" class="focused-mode-help"></section>')}
 function renderModeHelp(){ensureModeHelp();const el=document.getElementById('focusedModeHelp');if(!el)return;if(state.radarMode==='mexc'){el.innerHTML=`<div class="mode-help-icon">↗</div><div><strong>MEXC EXTREME · RAVE-TYPE</strong><p>${state.lang==='ru'?'Ищем не +10–20%, а структуру перед редким вертикальным движением: MEXC-only рынок, долгий пол/сжатая база, затем резкое ускорение объёма до того, как цена уже улетела. TRX, LINK, XRP, TAO, золото и другие крупные/синтетические рынки здесь намеренно скрыты.':'Looks for an obscure MEXC-only market with a compressed floor/base and volume ignition before price expansion. Major-CEX and synthetic markets are intentionally hidden.'}</p><small>${state.lang==='ru'?'Цена одной монеты сама по себе не важна: $0.01 не «дешевле» $1 без учёта supply/float. Score показывает редкость структуры, а не обещание 100×.':'Unit price alone is not cheapness. Score ranks structural asymmetry; it is not a 100x forecast.'}</small></div>`}else{el.innerHTML=`<div class="mode-help-icon">◈</div><div><strong>VETTED DEX</strong><p>${state.lang==='ru'?'Здесь только Solana DEX-токены возрастом 30–365 дней, которые прошли Jupiter Verified, organic/liquidity, holder concentration, mint/freeze и major-CEX проверки. Свежие Pump.fun сюда не попадают.':'Only 30–365 day Solana DEX assets that pass Jupiter, liquidity, holder, authority and major-CEX checks.'}</p><small>${state.lang==='ru'?'VETTED SCORE = качество и отсутствие очевидных красных флагов. Это не оценка будущих иксов.':'VETTED SCORE measures current eligibility/quality, not future multiples.'}</small></div>`}}
 const oldSwitch=window.switchRadarMode||switchRadarMode;window.switchRadarMode=switchRadarMode=function(mode){const out=oldSwitch(mode);setTimeout(renderModeHelp,0);return out};
 function stageLabel(s){const ru={IGNITION:'IGNITION · ОБЪЁМ ПРОСЫПАЕТСЯ',DORMANT_BASE:'DORMANT BASE · ЕЩЁ СПИТ',EARLY_FLOW:'EARLY FLOW · РАННИЙ ПОТОК',NOT_READY:'НЕ ГОТОВ'};return state.lang==='ru'?(ru[s]||s):s}
 renderMexcPumpFocused=function renderRaveMexc(){if(state.radarMode!=='mexc')return;const box=$('mexcExtremeList');if(!box)return;const panel=document.querySelector('.mexc-panel .panel-head');if(panel){const kicker=panel.querySelector('.panel-kicker'),h=panel.querySelector('h2'),p=panel.querySelector('p');if(kicker)kicker.textContent='RAVE-TYPE EXTREME STRUCTURE';if(h)h.textContent='MEXC EXTREME MULTIPLIER RADAR';if(p)p.textContent=state.lang==='ru'?'Не обычный momentum. Ищем базу у пола + раннее зажигание объёма до вертикального движения.':'Not ordinary momentum: floor/base + early volume ignition before vertical expansion.'}
  const list=(state.extremeData?.mexc||[]).filter(m=>m.extreme?.eligible&&(m.extreme.score||0)>=55&&!m.extreme.alreadyMoved&&!m.extreme.profile?.priorMoonshot).sort((a,b)=>(b.extreme.raveLike-a.extreme.raveLike)||(b.extreme.score-a.extreme.score)).slice(0,20);
  box.innerHTML=list.length?list.map(m=>{const e=m.extreme,p=e.profile||{},k=m.deep?.kline||{},reasons=(e.reasons||[]).slice(0,5).map(r=>`<span>${esc(state.lang==='ru'?(reasonRu[r]||r.replaceAll('_',' ')):r.replaceAll('_',' '))}</span>`).join('');return`<article class="rave-card"><div class="rave-head"><div><strong>${esc(m.base)}/${esc(m.quote)}</strong><small>${fmtExtremePrice(m.price)} · 24h ${Number(m.change24h)>=0?'+':''}${Number(m.change24h||0).toFixed(1)}%</small></div><div class="rave-score"><b>${e.score}</b><span>RAVE DNA</span></div></div><div class="rave-stage ${e.raveLike?'hot':''}">${esc(stageLabel(e.stage))}</div><div class="rave-metrics"><div><span>AGE</span><b>${p.ageDays?Math.round(p.ageDays)+'d':'—'}</b></div><div><span>BASE 7D</span><b>${pct(p.range7Pct)}</b></div><div><span>BASE 30D</span><b>${pct(p.range30Pct)}</b></div><div><span>FROM 90D FLOOR</span><b>${pct(p.floorDistance90Pct)}</b></div><div><span>VOL IGNITION</span><b>${k.volAccel?Number(k.volAccel).toFixed(1)+'×':'—'}</b></div><div><span>DEPTH ±2%</span><b>${fmtExtremeMoney(p.depth2Usd||0)}</b></div></div><div class="rave-why">${reasons}</div><div class="rave-foot"><span>${state.lang==='ru'?'Major CEX: нет · прошлый moonshot: нет':'Major CEX: none · prior moonshot: none'}</span><a href="${esc(m.url||'#')}" target="_blank" rel="noopener noreferrer">${state.lang==='ru'?'Открыть MEXC ↗':'Open MEXC ↗'}</a></div></article>`}).join(''):`<div class="rave-empty"><strong>${state.lang==='ru'?'Сейчас RAVE-type setup нет.':'No RAVE-type setup right now.'}</strong><span>${state.lang==='ru'?'Это нормально. Крупные монеты и обычные +5–20% momentum-сигналы больше не заполняют список. Радар ждёт редкую комбинацию: пол + сжатие + объём до движения.':'Large caps and ordinary momentum no longer fill this list. The radar waits for floor + compression + ignition before expansion.'}</span></div>`;
 }
 const oldExtremeRender=renderExtremePanel;renderExtremePanel=function(){oldExtremeRender();renderMexcPumpFocused()};
 const oldAlert=alertTitle;alertTitle=function(a){if(a?.title==='MEXC_RAVE_TYPE')return state.lang==='ru'?'MEXC: RAVE-type структура проснулась':'MEXC: RAVE-type structure woke up';return oldAlert(a)};
 const css=document.createElement('style');css.textContent=`.focused-mode-help{display:flex;gap:12px;align-items:flex-start;border:1px solid rgba(93,228,255,.16);background:linear-gradient(135deg,rgba(93,228,255,.035),rgba(255,255,255,.012));padding:12px 14px;border-radius:12px;margin:-2px 0 12px}.mode-help-icon{font-size:23px;color:#5de4ff;line-height:1}.focused-mode-help strong{font-size:10px;letter-spacing:.08em}.focused-mode-help p{font-size:9px;line-height:1.5;color:#bfd0d9;margin:4px 0}.focused-mode-help small{font-size:8px;line-height:1.45;color:var(--muted)}.mexc-list{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;padding:12px!important}.rave-card{border:1px solid var(--line);border-radius:12px;padding:12px;background:rgba(255,255,255,.014)}.rave-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.rave-head strong{display:block;font-size:13px}.rave-head small{display:block;color:var(--muted);font-size:8px;margin-top:4px}.rave-score{text-align:right}.rave-score b{display:block;font-size:20px;color:#d8ff75}.rave-score span{font-size:7px;color:var(--muted)}.rave-stage{display:inline-block;margin:9px 0 8px;border:1px solid var(--line);border-radius:999px;padding:4px 7px;font-size:7px;font-weight:900;color:#a9bac4}.rave-stage.hot{color:#73f2b8;border-color:rgba(115,242,184,.3);background:rgba(115,242,184,.045)}.rave-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.rave-metrics div{border:1px solid rgba(255,255,255,.045);border-radius:8px;padding:7px}.rave-metrics span{display:block;font-size:6px;color:var(--muted);letter-spacing:.06em}.rave-metrics b{display:block;font-size:9px;margin-top:3px}.rave-why{display:flex;gap:4px;flex-wrap:wrap;margin-top:8px}.rave-why span{border:1px solid rgba(93,228,255,.14);border-radius:999px;padding:4px 6px;font-size:7px;color:#a8dce8}.rave-foot{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:9px;padding-top:8px;border-top:1px solid var(--line)}.rave-foot span{font-size:7px;color:var(--muted)}.rave-foot a{font-size:8px;color:#73f2b8;text-decoration:none;font-weight:800}.rave-empty{grid-column:1/-1;padding:20px 6px}.rave-empty strong,.rave-empty span{display:block}.rave-empty strong{font-size:11px}.rave-empty span{font-size:9px;line-height:1.55;color:var(--muted);margin-top:6px}@media(max-width:760px){.mexc-list{grid-template-columns:1fr}.focused-mode-help{margin-top:0}.rave-card{padding:11px}.rave-metrics{grid-template-columns:repeat(3,1fr)}}`;document.head.appendChild(css);
 setTimeout(()=>{renderModeHelp();if(state.radarMode==='mexc')renderMexcPumpFocused()},350);
})();
