// NEXUS ALPHA — animated Retina canvas market map.
(function(){
  if(window.__nexusCanvasMapLoaded)return;window.__nexusCanvasMapLoaded=true;window.__nexusMarketMapLoaded=true;
  const ru=()=>window.state?.lang==='ru';
  const tx=(a,b)=>ru()?a:b;
  const API=window.API_BASE||'';
  const MM={kind:'market',start:0,period:'1h',items:[],nodes:[],loading:false,updatedAt:0,raf:0,dpr:1,pointer:null,drag:null,lastTs:0};
  if(window.state)state.marketMap=MM;
  document.body.classList.add('nexus-map-only');
  document.getElementById('nexusMarketMap')?.remove();
  document.getElementById('radarModeSwitch')?.remove();
  document.getElementById('extremeWorkspace')?.remove();
  document.querySelectorAll('.mexc-panel,.extreme-panel,.radar-mode-switch').forEach(x=>x.remove());
  const shell=document.querySelector('main.shell'); if(!shell)return;

  const section=document.createElement('section'); section.id='nexusMarketMap'; section.className='nx-map';
  section.innerHTML=`
    <div class="nx-bar">
      <div class="nx-tabs" id="nxTabs"><button class="active" data-kind="market">${tx('РЫНОК','MARKET')}</button><button data-kind="pump">PUMP.FUN</button><button data-kind="dex">DEX VETTED</button><button data-kind="precex">PRE-CEX</button></div>
      <div class="nx-live"><i></i>LIVE</div>
    </div>
    <div class="nx-ranks" id="nxRanks"></div>
    <div class="nx-head"><div><small>NEXUS MARKET MAP</small><h1 id="nxTitle">TOP #1–100</h1></div><span id="nxMeta">—</span></div>
    <div class="nx-stage" id="nxStage"><canvas id="nxCanvas"></canvas><div class="nx-loader" id="nxLoader"><b></b>${tx('ЗАГРУЖАЕМ РЫНОК','LOADING MARKET')}</div><div class="nx-empty" id="nxEmpty"></div></div>
    <div class="nx-foot"><div class="nx-period" id="nxPeriod"><button class="active" data-p="1h">1H</button><button data-p="24h">24H</button><button data-p="7d">7D</button></div><div class="nx-help">${tx('Нажми на монету · перетащи пальцем','Tap a coin · drag with your finger')}</div></div>
    <div class="nx-sheet" id="nxSheet"><button id="nxClose">×</button><div id="nxSheetBody"></div></div>`;
  shell.prepend(section);

  const style=document.createElement('style'); style.textContent=`
    .nx-map{width:100%;box-sizing:border-box;padding:5px 7px 10px;background:#020304;color:#f7f9fb;min-height:calc(100dvh - 70px)}
    .nx-bar,.nx-head,.nx-foot,.nx-ranks{max-width:1600px;margin-left:auto;margin-right:auto}.nx-bar{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:5px}.nx-tabs,.nx-ranks,.nx-period{display:flex;gap:5px;overflow:auto;scrollbar-width:none}.nx-tabs::-webkit-scrollbar,.nx-ranks::-webkit-scrollbar{display:none}.nx-tabs button,.nx-ranks button,.nx-period button{border:1px solid rgba(255,255,255,.08);background:#080b0f;color:#7f8b98;border-radius:999px;padding:7px 11px;font:800 9px/1 system-ui;white-space:nowrap}.nx-tabs button.active{color:#f8fffc;border-color:rgba(82,242,174,.38);background:rgba(34,91,69,.28)}.nx-live{font:900 8px/1 system-ui;color:#6af0b4;letter-spacing:.12em}.nx-live i{display:inline-block;width:6px;height:6px;border-radius:50%;background:#61efb0;box-shadow:0 0 12px #61efb0;margin-right:5px}.nx-ranks{margin-bottom:3px}.nx-ranks button{padding:5px 9px;font-size:8px}.nx-ranks button.active{color:#dffcff;border-color:rgba(87,224,255,.35);background:rgba(70,180,215,.08)}.nx-ranks.hide{display:none}
    .nx-head{display:flex;align-items:end;justify-content:space-between;padding:0 3px 4px}.nx-head small{font:900 7px/1 system-ui;letter-spacing:.22em;color:#63e4fa}.nx-head h1{margin:4px 0 0;font:900 17px/1 system-ui}.nx-head span{font:700 8px/1 system-ui;color:#687581}
    .nx-stage{position:relative;max-width:1600px;margin:0 auto;height:calc(100dvh - 205px);min-height:570px;max-height:1100px;overflow:hidden;background:radial-gradient(circle at 48% 44%,#0a0e12 0,#040609 45%,#010203 100%);border-radius:10px;touch-action:none;box-shadow:inset 0 0 85px rgba(0,0,0,.78)}#nxCanvas{position:absolute;inset:0;width:100%;height:100%;display:block}.nx-loader{position:absolute;inset:0;display:none;align-items:center;justify-content:center;gap:8px;background:rgba(2,3,4,.7);font:800 9px/1 system-ui;color:#81909d;letter-spacing:.12em;backdrop-filter:blur(2px)}.nx-loader.show{display:flex}.nx-loader b{width:13px;height:13px;border:2px solid #18313a;border-top-color:#5ee5ff;border-radius:50%;animation:nxspin .7s linear infinite}@keyframes nxspin{to{transform:rotate(1turn)}}.nx-empty{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);color:#66727d;font:700 9px/1.35 system-ui;text-align:center;pointer-events:none}
    .nx-foot{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:6px}.nx-period button{border-radius:8px;min-width:52px;font-size:11px}.nx-period button.active{color:#fff;background:#e65058;border-color:#e65058;box-shadow:0 0 20px rgba(230,80,88,.18)}.nx-help{font:700 8px/1 system-ui;color:#52606c}.nx-sheet{position:fixed;z-index:100;left:50%;bottom:12px;width:min(560px,calc(100% - 18px));padding:17px;box-sizing:border-box;border:1px solid rgba(255,255,255,.1);border-radius:18px;background:rgba(7,10,14,.98);box-shadow:0 24px 80px rgba(0,0,0,.72);transform:translate(-50%,125%);opacity:0;transition:.2s ease}.nx-sheet.show{transform:translate(-50%,0);opacity:1}.nx-sheet>button{position:absolute;right:8px;top:6px;border:0;background:none;color:#82909d;font-size:26px}.nx-coin{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding-right:24px}.nx-coin img{width:44px;height:44px;border-radius:50%;object-fit:cover}.nx-coin small,.nx-coin b{display:block;color:#7a8794;font-size:9px}.nx-coin h2{font-size:19px;margin:2px 0}.nx-coin>strong{font-size:18px}.nx-pos{color:#65efb3}.nx-neg{color:#ff6d84}.nx-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:14px}.nx-stats div{border:1px solid rgba(255,255,255,.07);border-radius:10px;padding:9px;background:rgba(255,255,255,.018)}.nx-stats span{display:block;font-size:7px;color:#697683;text-transform:uppercase}.nx-stats b{display:block;margin-top:4px;font-size:11px}
    @media(max-width:760px){.nexus-map-only .topbar{padding:9px 10px}.nexus-map-only .brand-copy small,.nexus-map-only .latency-chip{display:none}.nx-map{padding:4px 3px 8px}.nx-stage{height:calc(100dvh - 193px);min-height:555px;border-radius:6px}.nx-head h1{font-size:16px}.nx-help{display:none}.nx-stats{grid-template-columns:repeat(2,1fr)}}`;
  document.head.appendChild(style);

  const canvas=document.getElementById('nxCanvas'),ctx=canvas.getContext('2d',{alpha:false}),stage=document.getElementById('nxStage');
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const hash=s=>{let h=2166136261;for(const ch of String(s||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0)/4294967295};
  const money=v=>{v=Number(v)||0;if(v>=1e12)return'$'+(v/1e12).toFixed(2)+'T';if(v>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(v>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(v>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toFixed(2)};
  const fmtPrice=v=>{v=Number(v)||0;if(!v)return'—';if(v>=1000)return'$'+v.toLocaleString(undefined,{maximumFractionDigits:2});if(v>=1)return'$'+v.toFixed(3);if(v>=.01)return'$'+v.toFixed(5);return'$'+v.toPrecision(4)};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  function buildRanks(){const box=document.getElementById('nxRanks');box.innerHTML=Array.from({length:10},(_,i)=>`<button data-s="${i*100}" class="${i===0?'active':''}">${i*100+1}–${i*100+100}</button>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{MM.start=+b.dataset.s;box.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));load()})} buildRanks();
  document.querySelectorAll('#nxTabs button').forEach(b=>b.onclick=()=>{MM.kind=b.dataset.kind;document.querySelectorAll('#nxTabs button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('nxRanks').classList.toggle('hide',MM.kind!=='market');load()});
  document.querySelectorAll('#nxPeriod button').forEach(b=>b.onclick=()=>{MM.period=b.dataset.p;document.querySelectorAll('#nxPeriod button').forEach(x=>x.classList.toggle('active',x===b));rebuildSprites()});
  document.getElementById('nxClose').onclick=()=>document.getElementById('nxSheet').classList.remove('show');

  function change(c){return Number(MM.period==='1h'?c.change1h:MM.period==='7d'?c.change7d:c.change24h)||0}
  function logoCandidates(c){const s=String(c.symbol||'').toLowerCase();return [c.image,c.logo,s?`https://assets.coincap.io/assets/icons/${encodeURIComponent(s)}@2x.png`:'',c.nameid?`https://c2.coinlore.com/img/25x25/${encodeURIComponent(c.nameid)}.png`:''].filter(Boolean)}
  function tokenItem(t,kind){const d=t.dex||{},liq=+d.liquidityUsd||0,cap=+d.marketCap||+d.fdv||+t.pump?.marketCapUsd||liq*2.5;return{id:t.mint,symbol:String(t.symbol||'?').toUpperCase(),name:t.name||t.symbol||'Token',price:+d.priceUsd||0,marketCap:cap||1,volume24:+d.volumeH24||+d.volumeH6||+d.volumeH1||0,change1h:+d.changeH1||+d.changeM5||0,change24h:+d.changeH24||+d.change24h||+d.changeH1||0,change7d:+d.changeH24||+d.change24h||0,image:t.image||t.logo||'',raw:t,kind}}

  async function load(){if(MM.loading)return;MM.loading=true;document.getElementById('nxLoader').classList.add('show');document.getElementById('nxEmpty').textContent='';try{let items=[],updated=Date.now();if(MM.kind==='market'){const r=await fetch(`${API}/api/market-map?start=${MM.start}&limit=100`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();items=d.coins||[];updated=d.generatedAt||Date.now()}else if(MM.kind==='pump'){const r=await fetch(`${API}/api/radar-v3?limit=800&maxAgeHours=24`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();items=(d.tokens||[]).filter(t=>t.pump||String(t.source||'').toLowerCase().includes('pump')).map(t=>tokenItem(t,'pump')).sort((a,b)=>b.marketCap-a.marketCap).slice(0,220);updated=d.generatedAt||Date.now()}else{const r=await fetch(`${API}/api/vetted?limit=500`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();let rows=d.tokens||[];if(MM.kind==='precex')rows=rows.filter(t=>t.vetted?.cex?.preCexCandidate||t.vetted?.cex?.projectClaimDetected);items=rows.map(t=>tokenItem(t,MM.kind)).sort((a,b)=>b.marketCap-a.marketCap).slice(0,220);updated=d.generatedAt||Date.now()}MM.items=items;MM.updatedAt=updated;updateHead();seedNodes()}catch(e){MM.items=[];MM.nodes=[];document.getElementById('nxEmpty').textContent=tx('Источник временно недоступен','Source temporarily unavailable')+' · '+e.message}finally{MM.loading=false;document.getElementById('nxLoader').classList.remove('show')}}

  function updateHead(){const t=document.getElementById('nxTitle');if(MM.kind==='market')t.textContent=`TOP #${MM.start+1}–${MM.start+100}`;else if(MM.kind==='pump')t.textContent='PUMP.FUN · LIVE';else if(MM.kind==='dex')t.textContent='DEX VETTED';else t.textContent='PRE-CEX';document.getElementById('nxMeta').textContent=`${MM.items.length} ${tx('активов','assets')} · ${new Date(MM.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`}

  function resize(){const r=stage.getBoundingClientRect();MM.dpr=Math.min(3,Math.max(1,window.devicePixelRatio||1));canvas.width=Math.round(r.width*MM.dpr);canvas.height=Math.round(r.height*MM.dpr);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(MM.dpr,0,0,MM.dpr,0,0);if(MM.nodes.length)confineAll()}
  function radii(items,w,h){const n=items.length||1,vals=items.map(x=>Math.log10(Math.max(1,+x.marketCap||+x.volume24||1))),lo=Math.min(...vals),hi=Math.max(...vals),mobile=w<650,base=Math.sqrt(w*h/n);return vals.map((v,i)=>{const q=hi>lo?(v-lo)/(hi-lo):.5;let r=(mobile?7.5:9)+Math.pow(q,1.75)*(mobile?53:78);r*=clamp(base/(mobile?25:29),.72,1.18);const move=Math.min(.16,Math.abs(change(items[i]))/100);return r*(1+move)})}
  function seedNodes(){resize();const w=stage.clientWidth,h=stage.clientHeight,rs=radii(MM.items,w,h),cx=w/2,cy=h/2;MM.nodes=MM.items.map((item,i)=>{const rnd=hash(item.id||item.symbol),a=i*2.399963+rnd*6.28,spread=Math.sqrt(i+1)*Math.min(w,h)*.026,r=rs[i];return{item,r,x:clamp(cx+Math.cos(a)*spread,r,w-r),y:clamp(cy+Math.sin(a)*spread,r,h-r),vx:(rnd-.5)*.13/(1+r*.012),vy:(hash((item.id||item.symbol)+'v')-.5)*.13/(1+r*.012),sprite:null,img:null,imgIndex:0,dirty:true}});preloadImages();for(let i=0;i<130;i++)physics(.7,true);rebuildSprites()}
  function preloadImages(){for(const n of MM.nodes){const urls=logoCandidates(n.item);if(!urls.length)continue;const img=new Image();n.img=img;const tryNext=()=>{const u=urls[n.imgIndex++];if(!u)return;n.img.onload=()=>{n.dirty=true};n.img.onerror=tryNext;n.img.src=u};tryNext()}}

  function bubbleColors(ch){const a=Math.abs(ch);if(a<.35)return{c0:'#171c22',c1:'#0b0f14',edge:'rgba(126,143,159,.38)',glow:'rgba(112,134,154,.06)',txt:'#c7d0d8'};if(ch>0){const k=clamp((a-.35)/18,0,1);return{c0:`rgb(${18+10*k},${52+70*k},${38+32*k})`,c1:`rgb(${7+4*k},${25+35*k},${18+16*k})`,edge:`rgba(55,255,143,${.42+.46*k})`,glow:`rgba(33,255,126,${.08+.38*k})`,txt:'#b7ffd1'}}const k=clamp((a-.35)/18,0,1);return{c0:`rgb(${62+62*k},${20+10*k},${29+18*k})`,c1:`rgb(${28+30*k},${8+7*k},${13+10*k})`,edge:`rgba(255,71,99,${.42+.46*k})`,glow:`rgba(255,42,78,${.08+.34*k})`,txt:'#ffc0ca'}}
  function makeSprite(n){const r=n.r,pad=Math.max(5,Math.min(15,r*.18)),s=Math.ceil((r+pad)*2),dpr=Math.min(2.5,MM.dpr),c=document.createElement('canvas');c.width=Math.ceil(s*dpr);c.height=Math.ceil(s*dpr);const g=c.getContext('2d');g.scale(dpr,dpr);const cx=s/2,cy=s/2,ch=change(n.item),col=bubbleColors(ch);g.clearRect(0,0,s,s);g.shadowColor=col.glow;g.shadowBlur=pad*1.6;g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);const grad=g.createRadialGradient(cx-r*.34,cy-r*.38,r*.08,cx,cy,r);grad.addColorStop(0,col.c0);grad.addColorStop(.68,col.c1);grad.addColorStop(1,'#05070a');g.fillStyle=grad;g.fill();g.shadowBlur=0;g.lineWidth=Math.max(.8,r*.035);g.strokeStyle=col.edge;g.stroke();g.beginPath();g.arc(cx-r*.22,cy-r*.26,r*.7,Math.PI*1.06,Math.PI*1.56);g.strokeStyle='rgba(255,255,255,.14)';g.lineWidth=Math.max(.6,r*.018);g.stroke();const img=n.img;if(img?.complete&&img.naturalWidth&&r>=10){const ir=clamp(r*.23,7,22),iy=cy-(r>=28?ir*.78:0);g.save();g.beginPath();g.arc(cx,iy,ir,0,Math.PI*2);g.clip();g.drawImage(img,cx-ir,iy-ir,ir*2,ir*2);g.restore();g.strokeStyle='rgba(255,255,255,.14)';g.lineWidth=.7;g.beginPath();g.arc(cx,iy,ir,0,Math.PI*2);g.stroke()}
    g.textAlign='center';g.textBaseline='middle';g.fillStyle='#f4f7fa';g.shadowColor='rgba(0,0,0,.75)';g.shadowBlur=3;
    if(r>=17){const fs=clamp(r*.29,8,17);g.font=`900 ${fs}px system-ui,-apple-system,sans-serif`;g.fillText(String(n.item.symbol||'?').slice(0,r<24?4:7),cx,cy+(r>=28?r*.12:0),r*1.55)}
    if(r>=27){const fs=clamp(r*.19,7,12),label=(ch>=0?'+':'')+ch.toFixed(Math.abs(ch)>=100?0:1)+'%';g.font=`800 ${fs}px system-ui,-apple-system,sans-serif`;g.fillStyle=col.txt;g.fillText(label,cx,cy+r*.42,r*1.45)}
    n.sprite={canvas:c,w:s,h:s};n.dirty=false}
  function rebuildSprites(){for(const n of MM.nodes){n.dirty=true;makeSprite(n)}}

  function confineAll(){const w=stage.clientWidth,h=stage.clientHeight;for(const n of MM.nodes){n.x=clamp(n.x,n.r,w-n.r);n.y=clamp(n.y,n.r,h-n.r)}}
  function physics(dt,settle=false){const a=MM.nodes,w=stage.clientWidth,h=stage.clientHeight,cx=w/2,cy=h/2;for(let i=0;i<a.length;i++){const n=a[i];if(MM.drag===n)continue;const seed=hash((n.item.id||n.item.symbol)+'d'),ang=(performance.now()/1000)*(seed>.5?1:-1)*(.035+.05*seed)+seed*6.28;n.vx+=Math.cos(ang)*.0018*dt;n.vy+=Math.sin(ang)*.0018*dt;n.vx+=(cx-n.x)*.0000045*dt;n.vy+=(cy-n.y)*.0000045*dt;if(MM.pointer?.down){const dx=n.x-MM.pointer.x,dy=n.y-MM.pointer.y,d=Math.hypot(dx,dy)||1,reach=n.r+70;if(d<reach&&MM.drag!==n){const f=(reach-d)/reach*.025;n.vx+=dx/d*f;n.vy+=dy/d*f}}}
    for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const x=a[i],y=a[j],dx=y.x-x.x,dy=y.y-x.y,d=Math.hypot(dx,dy)||.01,min=x.r+y.r+.7;if(d<min){const ov=min-d,nx=dx/d,ny=dy/d,ma=1/(x.r*x.r),mb=1/(y.r*y.r),sum=ma+mb;x.x-=nx*ov*(ma/sum);x.y-=ny*ov*(ma/sum);y.x+=nx*ov*(mb/sum);y.y+=ny*ov*(mb/sum);const rvx=y.vx-x.vx,rvy=y.vy-x.vy,sep=rvx*nx+rvy*ny;if(sep<0){const imp=-sep*.72;x.vx-=imp*nx*ma/sum;x.vy-=imp*ny*ma/sum;y.vx+=imp*nx*mb/sum;y.vy+=imp*ny*mb/sum}}}
    for(const n of a){if(MM.drag===n)continue;n.vx*=settle?.72:.994;n.vy*=settle?.72:.994;const max=.24+18/(n.r+12);const sp=Math.hypot(n.vx,n.vy);if(sp>max){n.vx=n.vx/sp*max;n.vy=n.vy/sp*max}n.x+=n.vx*dt;n.y+=n.vy*dt;if(n.x<n.r){n.x=n.r;n.vx=Math.abs(n.vx)*.82}else if(n.x>w-n.r){n.x=w-n.r;n.vx=-Math.abs(n.vx)*.82}if(n.y<n.r){n.y=n.r;n.vy=Math.abs(n.vy)*.82}else if(n.y>h-n.r){n.y=h-n.r;n.vy=-Math.abs(n.vy)*.82}}}
  function draw(){const w=stage.clientWidth,h=stage.clientHeight;ctx.setTransform(MM.dpr,0,0,MM.dpr,0,0);const bg=ctx.createRadialGradient(w*.48,h*.42,0,w*.5,h*.5,Math.max(w,h)*.72);bg.addColorStop(0,'#0a0e12');bg.addColorStop(.58,'#030507');bg.addColorStop(1,'#010203');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);for(const n of MM.nodes){if(n.dirty||!n.sprite)makeSprite(n);const s=n.sprite;ctx.drawImage(s.canvas,n.x-s.w/2,n.y-s.h/2,s.w,s.h)}}
  function loop(ts){const dt=MM.lastTs?clamp((ts-MM.lastTs)/16.67,.35,1.8):1;MM.lastTs=ts;physics(dt);draw();MM.raf=requestAnimationFrame(loop)}

  function nodeAt(x,y){let hit=null,best=1e9;for(const n of MM.nodes){const d=Math.hypot(x-n.x,y-n.y);if(d<=n.r&&d<best){hit=n;best=d}}return hit}
  function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:p.clientX-r.left,y:p.clientY-r.top}}
  canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);const p=point(e),n=nodeAt(p.x,p.y);MM.pointer={...p,down:true,startX:p.x,startY:p.y};MM.drag=n;if(n){n.vx=n.vy=0}});
  canvas.addEventListener('pointermove',e=>{if(!MM.pointer?.down)return;const p=point(e);MM.pointer.x=p.x;MM.pointer.y=p.y;if(MM.drag){MM.drag.x=clamp(p.x,MM.drag.r,stage.clientWidth-MM.drag.r);MM.drag.y=clamp(p.y,MM.drag.r,stage.clientHeight-MM.drag.r)}});
  canvas.addEventListener('pointerup',e=>{const p=point(e),drag=MM.drag,moved=MM.pointer?Math.hypot(p.x-MM.pointer.startX,p.y-MM.pointer.startY):99;if(drag){drag.vx=(p.x-(MM.pointer?.x||p.x))*.08;drag.vy=(p.y-(MM.pointer?.y||p.y))*.08}MM.pointer={...p,down:false};MM.drag=null;if(drag&&moved<9)openItem(drag.item)});
  canvas.addEventListener('pointercancel',()=>{MM.pointer=null;MM.drag=null});

  function openItem(c){if(c.raw&&typeof window.renderDetail==='function'){window.renderDetail(c.raw);return}const sheet=document.getElementById('nxSheet'),body=document.getElementById('nxSheetBody'),ch=change(c),logo=logoCandidates(c)[0]||'';body.innerHTML=`<div class="nx-coin">${logo?`<img src="${esc(logo)}" alt="">`:''}<div><small>#${c.rank||'—'}</small><h2>${esc(c.name)}</h2><b>${esc(c.symbol)}</b></div><strong class="${ch>=0?'nx-pos':'nx-neg'}">${ch>=0?'+':''}${ch.toFixed(2)}%</strong></div><div class="nx-stats"><div><span>${tx('Цена','Price')}</span><b>${fmtPrice(c.price)}</b></div><div><span>${tx('Капитализация','Market cap')}</span><b>${money(c.marketCap)}</b></div><div><span>${tx('Объём 24ч','24h volume')}</span><b>${money(c.volume24)}</b></div><div><span>1H</span><b>${(+c.change1h>=0?'+':'')+(+c.change1h||0).toFixed(2)}%</b></div><div><span>24H</span><b>${(+c.change24h>=0?'+':'')+(+c.change24h||0).toFixed(2)}%</b></div><div><span>7D</span><b>${(+c.change7d>=0?'+':'')+(+c.change7d||0).toFixed(2)}%</b></div></div>`;sheet.classList.add('show')}

  new ResizeObserver(()=>{resize();rebuildSprites()}).observe(stage);
  load();resize();cancelAnimationFrame(MM.raf);MM.raf=requestAnimationFrame(loop);setInterval(()=>load(),45000);
})();
