// NEXUS ALPHA — stable premium Market Wall. No bubble physics.
(()=>{
  const API=window.NEXUS_API||'https://murdilimax-live-earth-api.onrender.com';
  let lang=window.NEXUS_LANG||localStorage.getItem('nexus-lang')||'ru';
  const T=(r,e)=>lang==='ru'?r:e,$=id=>document.getElementById(id);
  const app=$('app');if(!app)return;
  const S={kind:'market',start:0,period:'1h',items:[],loading:false,updated:0};
  const finite=v=>Number.isFinite(Number(v)),num=v=>Number(v)||0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>{v=num(v);if(v>=1e12)return'$'+(v/1e12).toFixed(2)+'T';if(v>=1e9)return'$'+(v/1e9).toFixed(2)+'B';if(v>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(v>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return v?'$'+v.toFixed(2):'—'};
  const price=v=>{v=num(v);if(!v)return'—';if(v>=1000)return'$'+v.toLocaleString(undefined,{maximumFractionDigits:2});if(v>=1)return'$'+v.toFixed(3);if(v>=.01)return'$'+v.toFixed(5);return'$'+v.toPrecision(4)};
  const change=c=>{const k=S.period==='5m'?'change5m':S.period==='15m'?'change15m':S.period==='1h'?'change1h':S.period==='24h'?'change24h':'change30d';return finite(c[k])?Number(c[k]):null};
  const logo=c=>{const s=String(c.symbol||'').toLowerCase();return c.image||c.logo||(s?`https://assets.coincap.io/assets/icons/${encodeURIComponent(s)}@2x.png`:'')||(c.nameid?`https://c2.coinlore.com/img/25x25/${encodeURIComponent(c.nameid)}.png`:'')};
  function normalMarket(x){return{id:x.id||x.symbol,rank:num(x.rank),symbol:String(x.symbol||'?').toUpperCase(),name:x.name||x.symbol||'Coin',nameid:x.nameid||'',logo:x.logo||'',price:num(x.price||x.price_usd),marketCap:num(x.marketCap||x.market_cap_usd),volume24:num(x.volume24),change5m:finite(x.change5m)?Number(x.change5m):null,change15m:finite(x.change15m)?Number(x.change15m):null,change1h:finite(x.change1h??x.percent_change_1h)?Number(x.change1h??x.percent_change_1h):null,change24h:finite(x.change24h??x.percent_change_24h)?Number(x.change24h??x.percent_change_24h):null,change30d:finite(x.change30d)?Number(x.change30d):null,kind:'market'}}
  function normalToken(t,kind){const d=t.dex||{},liq=num(d.liquidityUsd),cap=num(d.marketCap||d.fdv||t.pump?.marketCapUsd)||liq*2.5;return{id:t.mint||t.symbol,symbol:String(t.symbol||'?').toUpperCase(),name:t.name||t.symbol||'Token',image:t.image||t.logo||'',price:num(d.priceUsd),marketCap:cap||1,volume24:num(d.volumeH24||d.volumeH6||d.volumeH1),change5m:finite(d.changeM5)?Number(d.changeM5):null,change15m:finite(d.changeM15)?Number(d.changeM15):null,change1h:finite(d.changeH1)?Number(d.changeH1):null,change24h:finite(d.changeH24??d.change24h)?Number(d.changeH24??d.change24h):null,change30d:null,kind,raw:t}}

  app.innerHTML=`<section class="wall-shell">
    <div class="wall-toolbar"><div class="tabs" id="tabs"><button class="on" data-kind="market">${T('РЫНОК','MARKET')}</button><button data-kind="pump">PUMP.FUN</button><button data-kind="dex">DEX VETTED</button><button data-kind="precex">PRE-CEX</button></div><div class="live-dot"><i></i>LIVE</div></div>
    <div class="ranks" id="ranks"></div>
    <div class="wall-head"><div><small>NEXUS MARKET WALL</small><h1 id="title">TOP #1–100</h1></div><div class="head-right"><span id="meta">—</span><b id="sentiment">—</b></div></div>
    <div class="periods" id="periods"><button data-p="5m">5M</button><button data-p="15m">15M</button><button class="on" data-p="1h">1H</button><button data-p="24h">1D</button><button data-p="30d">1M</button></div>
    <div class="wall" id="wall"><div class="loader" id="loader"><b></b>${T('ЗАГРУЖАЕМ ДАННЫЕ','LOADING DATA')}</div></div>
    <div class="legend"><span><i class="up"></i>${T('РОСТ','UP')}</span><span><i class="flat"></i>${T('ФЛЭТ','FLAT')}</span><span><i class="down"></i>${T('ПАДЕНИЕ','DOWN')}</span><em id="note"></em></div>
    <div class="sheet" id="sheet"><button id="close">×</button><div id="sheetBody"></div></div>
  </section>`;

  const style=document.createElement('style');style.textContent=`
  .wall-shell{padding:8px 8px 18px;background:radial-gradient(circle at 50% 0,#081118 0,#020405 28%,#010203 70%);min-height:calc(100dvh - 70px);color:#f7fafc}.wall-toolbar,.ranks,.wall-head,.periods,.wall,.legend{max-width:1500px;margin-left:auto;margin-right:auto}.wall-toolbar{display:flex;justify-content:space-between;align-items:center;gap:8px}.tabs,.ranks,.periods{display:flex;gap:6px;overflow:auto;scrollbar-width:none}.tabs::-webkit-scrollbar,.ranks::-webkit-scrollbar,.periods::-webkit-scrollbar{display:none}.tabs button,.ranks button,.periods button{border:1px solid rgba(255,255,255,.08);background:rgba(8,12,16,.92);color:#7f8b96;border-radius:999px;padding:9px 13px;font:800 9px/1 system-ui;white-space:nowrap}.tabs button.on{color:#dfffee;border-color:rgba(83,239,179,.35);background:linear-gradient(180deg,rgba(39,102,77,.34),rgba(20,57,44,.18));box-shadow:0 0 20px rgba(72,235,170,.07)}.live-dot{color:#64edb3;font:900 8px/1 system-ui;letter-spacing:.16em}.live-dot i{display:inline-block;width:6px;height:6px;border-radius:50%;background:#64edb3;box-shadow:0 0 12px #64edb3;margin-right:6px}.ranks{padding:7px 0 3px}.ranks button{padding:7px 11px;font-size:8px}.ranks button.on{color:#dff9ff;border-color:rgba(78,213,255,.3);background:rgba(37,134,165,.1)}.ranks.hidden{display:none}.wall-head{display:flex;align-items:end;justify-content:space-between;padding:5px 3px 7px}.wall-head small{color:#67dff7;font:900 7px/1 system-ui;letter-spacing:.23em}.wall-head h1{margin:5px 0 0;font:900 22px/1 system-ui}.head-right{text-align:right}.head-right span{display:block;color:#66737e;font:700 8px/1.2 system-ui}.head-right b{display:inline-block;margin-top:4px;padding:4px 7px;border-radius:999px;background:#0a0f13;color:#8b98a4;font:800 8px/1 system-ui}.periods{padding:0 0 8px}.periods button{border-radius:10px;min-width:50px;font-size:10px}.periods button.on{color:#fff;background:#e6535c;border-color:#e6535c;box-shadow:0 0 18px rgba(230,83,92,.17)}
  .wall{position:relative;display:grid;grid-template-columns:repeat(12,minmax(0,1fr));grid-auto-rows:72px;gap:5px;min-height:540px}.loader{grid-column:1/-1;min-height:420px;display:flex;align-items:center;justify-content:center;gap:8px;color:#6f7d88;font:800 9px/1 system-ui;letter-spacing:.12em}.loader b{width:15px;height:15px;border:2px solid #18242c;border-top-color:#62e6ff;border-radius:50%;animation:spin .65s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
  .tile{position:relative;overflow:hidden;border:1px solid var(--edge);border-radius:14px;background:linear-gradient(145deg,var(--bg1),var(--bg2));box-shadow:inset 0 1px 0 rgba(255,255,255,.055),inset 0 -25px 60px rgba(0,0,0,.25),0 8px 28px rgba(0,0,0,.23);padding:10px;cursor:pointer;isolation:isolate;transition:transform .14s ease,border-color .2s ease,filter .2s ease}.tile:active{transform:scale(.985)}.tile:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 20% 8%,rgba(255,255,255,.10),transparent 35%),linear-gradient(120deg,transparent 30%,rgba(255,255,255,.025) 50%,transparent 70%);pointer-events:none;z-index:-1}.tile.hot{box-shadow:inset 0 1px 0 rgba(255,255,255,.07),inset 0 -25px 60px rgba(0,0,0,.18),0 0 28px var(--glow),0 10px 34px rgba(0,0,0,.25)}.tile .topline{display:flex;align-items:center;gap:8px;min-width:0}.tile img,.coin-icon{width:28px;height:28px;border-radius:50%;object-fit:cover;background:#0b1014;box-shadow:0 0 0 1px rgba(255,255,255,.10),0 5px 14px rgba(0,0,0,.35);flex:0 0 auto}.tile .sym{min-width:0;font:900 13px/1 system-ui;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tile .rank{margin-left:auto;color:#71808c;font:800 7px/1 system-ui}.tile .chg{margin-top:7px;font:900 16px/1 system-ui;color:var(--text)}.tile .sub{display:flex;gap:7px;margin-top:6px;color:#84919c;font:700 7px/1 system-ui}.tile .name{display:none;color:#aeb8c2;font:700 8px/1.15 system-ui;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:7px}.tile .activity{position:absolute;left:0;bottom:0;height:3px;width:var(--act);background:var(--accent);box-shadow:0 0 10px var(--accent)}.tile.xl{grid-column:span 4;grid-row:span 3;padding:15px}.tile.xl img{width:46px;height:46px}.tile.xl .sym{font-size:22px}.tile.xl .chg{font-size:28px;margin-top:17px}.tile.xl .name{display:block;font-size:10px}.tile.xl .sub{font-size:9px;margin-top:9px}.tile.lg{grid-column:span 3;grid-row:span 2;padding:13px}.tile.lg img{width:38px;height:38px}.tile.lg .sym{font-size:18px}.tile.lg .chg{font-size:22px;margin-top:11px}.tile.lg .name{display:block}.tile.md{grid-column:span 2;grid-row:span 2}.tile.md img{width:32px;height:32px}.tile.md .sym{font-size:15px}.tile.md .chg{font-size:18px;margin-top:10px}.tile.sm{grid-column:span 2;grid-row:span 1}.tile.sm .sub{display:none}.tile.xs{grid-column:span 1;grid-row:span 1;padding:7px}.tile.xs img{width:22px;height:22px}.tile.xs .sym{font-size:9px}.tile.xs .rank,.tile.xs .sub{display:none}.tile.xs .chg{font-size:10px;margin-top:5px}.legend{display:flex;align-items:center;gap:12px;padding:10px 2px 0;color:#697681;font:800 7px/1 system-ui}.legend span{display:flex;align-items:center;gap:5px}.legend i{width:7px;height:7px;border-radius:2px}.legend .up{background:#36d98d}.legend .flat{background:#6f7c87}.legend .down{background:#f05269}.legend em{margin-left:auto;font-style:normal;color:#596671}
  .sheet{position:fixed;z-index:100;left:50%;bottom:12px;width:min(570px,calc(100% - 18px));padding:18px;border:1px solid rgba(255,255,255,.1);border-radius:19px;background:rgba(5,8,11,.985);box-shadow:0 25px 90px rgba(0,0,0,.78);transform:translate(-50%,130%);opacity:0;transition:.2s ease}.sheet.on{transform:translate(-50%,0);opacity:1}.sheet>button{position:absolute;right:8px;top:4px;border:0;background:none;color:#84919e;font-size:28px}.coin-head{display:grid;grid-template-columns:auto 1fr auto;gap:11px;align-items:center;padding-right:24px}.coin-head img{width:46px;height:46px;border-radius:50%;object-fit:cover;background:#111}.coin-head small,.coin-head b{display:block;color:#75818e;font-size:9px}.coin-head h2{margin:2px 0;font-size:19px}.coin-head>strong{font-size:18px}.pos{color:#67efb7}.neg{color:#ff6a7f}.muted{color:#7d8995!important}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:14px}.stats div{border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.018);padding:9px;border-radius:10px}.stats span{display:block;color:#687581;text-transform:uppercase;font-size:7px}.stats b{display:block;margin-top:4px;font-size:11px}
  @media(max-width:760px){.wall-shell{padding:6px 5px 14px;min-height:calc(100dvh - 65px)}.wall{grid-template-columns:repeat(6,minmax(0,1fr));grid-auto-rows:68px;gap:4px}.tile.xl{grid-column:span 3;grid-row:span 3}.tile.lg{grid-column:span 3;grid-row:span 2}.tile.md{grid-column:span 2;grid-row:span 2}.tile.sm{grid-column:span 2}.tile.xs{grid-column:span 1}.wall-head h1{font-size:19px}.stats{grid-template-columns:repeat(2,1fr)}.tile{border-radius:11px}.tile.xl .chg{font-size:24px}.tile.xl .sym{font-size:19px}}
  `;document.head.appendChild(style);

  const ranks=$('ranks');ranks.innerHTML=Array.from({length:10},(_,i)=>`<button data-s="${i*100}" class="${i===0?'on':''}">${i*100+1}–${i*100+100}</button>`).join('');
  ranks.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.start=+b.dataset.s;ranks.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));load()});
  document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{S.kind=b.dataset.kind;document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('on',x===b));ranks.classList.toggle('hidden',S.kind!=='market');load()});
  document.querySelectorAll('#periods button').forEach(b=>b.onclick=()=>{S.period=b.dataset.p;document.querySelectorAll('#periods button').forEach(x=>x.classList.toggle('on',x===b));render()});
  $('close').onclick=()=>$('sheet').classList.remove('on');$('langBtn').onclick=()=>{lang=lang==='ru'?'en':'ru';localStorage.setItem('nexus-lang',lang);location.reload()};

  async function fallback(){const r=await fetch(`https://api.coinlore.net/api/tickers/?start=${S.start}&limit=100`,{cache:'no-store'});if(!r.ok)throw Error('MARKET '+r.status);const d=await r.json();return{coins:(d.data||[]).map(normalMarket),generatedAt:Date.now()}}
  async function load(){if(S.loading)return;S.loading=true;$('wall').innerHTML=`<div class="loader"><b></b>${T('ЗАГРУЖАЕМ ДАННЫЕ','LOADING DATA')}</div>`;try{let items=[],updated=Date.now();if(S.kind==='market'){let d;try{const r=await fetch(`${API}/api/market-map?start=${S.start}&limit=100`,{cache:'no-store'});if(!r.ok)throw Error(String(r.status));d=await r.json()}catch{d=await fallback()}items=(d.coins||[]).map(normalMarket);updated=d.generatedAt||Date.now()}else if(S.kind==='pump'){const r=await fetch(`${API}/api/radar-v3?limit=500&maxAgeHours=24`,{cache:'no-store'});if(!r.ok)throw Error('API '+r.status);const d=await r.json();items=(d.tokens||[]).filter(t=>t.pump||String(t.source||'').toLowerCase().includes('pump')).map(t=>normalToken(t,'pump')).sort((a,b)=>b.marketCap-a.marketCap).slice(0,120);updated=d.generatedAt||Date.now()}else{const r=await fetch(`${API}/api/vetted?limit=500`,{cache:'no-store'});if(!r.ok)throw Error('API '+r.status);const d=await r.json();let rows=d.tokens||[];if(S.kind==='precex')rows=rows.filter(t=>t.vetted?.cex?.preCexCandidate||t.vetted?.cex?.projectClaimDetected);items=rows.map(t=>normalToken(t,S.kind)).sort((a,b)=>b.marketCap-a.marketCap).slice(0,120);updated=d.generatedAt||Date.now()}S.items=items;S.updated=updated;render()}catch(e){S.items=[];$('wall').innerHTML=`<div class="loader">${T('Источник временно недоступен','Source temporarily unavailable')} · ${esc(e.message)}</div>`}finally{S.loading=false}}

  function tileClass(i){if(i===0)return'xl';if(i<4)return'lg';if(i<12)return'md';if(i<36)return'sm';return'xs'}
  function palette(ch){if(ch===null)return{bg1:'#161a1f',bg2:'#080b0e',edge:'rgba(124,139,151,.28)',text:'#aab4bc',glow:'rgba(0,0,0,0)',accent:'#74818c'};const a=Math.abs(ch);if(a<.25)return{bg1:'#15191d',bg2:'#080b0e',edge:'rgba(124,139,151,.28)',text:'#c3cbd2',glow:'rgba(0,0,0,0)',accent:'#74818c'};if(ch>0){const k=clamp(a/15,0,1);return{bg1:`rgb(${12+6*k},${42+52*k},${29+32*k})`,bg2:`rgb(5,${18+18*k},${12+12*k})`,edge:`rgba(54,233,144,${.32+.38*k})`,text:'#73f0b1',glow:`rgba(37,232,132,${.05+.17*k})`,accent:'#39dc8f'}}const k=clamp(a/15,0,1);return{bg1:`rgb(${47+55*k},${16+7*k},${25+13*k})`,bg2:`rgb(${22+18*k},6,10)`,edge:`rgba(255,75,103,${.32+.38*k})`,text:'#ff8192',glow:`rgba(255,50,85,${.05+.15*k})`,accent:'#f05269'}}
  function render(){const items=S.items;const wall=$('wall');$('title').textContent=S.kind==='market'?`TOP #${S.start+1}–${S.start+100}`:S.kind==='pump'?'PUMP.FUN':S.kind==='dex'?'DEX VETTED':'PRE-CEX';$('meta').textContent=`${items.length} ${T('активов','assets')} · ${new Date(S.updated||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;const vals=items.map(change).filter(v=>v!==null),up=vals.filter(v=>v>0).length,down=vals.filter(v=>v<0).length;$('sentiment').textContent=vals.length?(up>down?`${T('РИСК-ОН','RISK-ON')} ${Math.round(up/vals.length*100)}%`:down>up?`${T('РИСК-ОФФ','RISK-OFF')} ${Math.round(down/vals.length*100)}%`:`${T('ФЛЭТ','FLAT')}`):'—';$('note').textContent=S.period==='5m'&&vals.length<items.length*.5?T('5M накапливается из live-снимков','5M is warming from live snapshots'):S.period==='30d'&&vals.length<items.length*.5?T('1M доступен не для всех активов','1M not available for every asset'):'';
    if(!items.length){wall.innerHTML=`<div class="loader">${T('Нет активов для этого режима','No assets for this view')}</div>`;return}
    const maxTurn=Math.max(...items.map(x=>x.marketCap?x.volume24/x.marketCap:0),.001);wall.innerHTML=items.map((c,i)=>{const ch=change(c),p=palette(ch),act=clamp((c.marketCap?c.volume24/c.marketCap:0)/maxTurn*100,3,100),img=logo(c),cls=tileClass(i),hot=ch!==null&&Math.abs(ch)>=5?' hot':'';return `<article class="tile ${cls}${hot}" data-i="${i}" style="--bg1:${p.bg1};--bg2:${p.bg2};--edge:${p.edge};--text:${p.text};--glow:${p.glow};--accent:${p.accent};--act:${act}%"><div class="topline">${img?`<img src="${esc(img)}" alt="" loading="lazy" onerror="this.style.visibility='hidden'">`:''}<div class="sym">${esc(c.symbol)}</div>${c.rank?`<div class="rank">#${c.rank}</div>`:''}</div><div class="chg">${ch===null?'—':`${ch>=0?'+':''}${ch.toFixed(Math.abs(ch)>=100?0:Math.abs(ch)>=10?1:2)}%`}</div><div class="name">${esc(c.name)}</div><div class="sub"><span>${money(c.marketCap)}</span><span>${money(c.volume24)} vol</span></div><div class="activity"></div></article>`}).join('');wall.querySelectorAll('.tile').forEach(el=>el.onclick=()=>show(items[+el.dataset.i]))}
  function show(c){const ch=change(c),img=logo(c),sheet=$('sheet'),cls=ch===null?'muted':ch>=0?'pos':'neg';$('sheetBody').innerHTML=`<div class="coin-head">${img?`<img src="${esc(img)}" alt="">`:''}<div><small>${c.rank?'#'+c.rank:String(c.kind||'').toUpperCase()}</small><h2>${esc(c.name)}</h2><b>${esc(c.symbol)}</b></div><strong class="${cls}">${ch===null?'—':`${ch>=0?'+':''}${ch.toFixed(2)}%`}</strong></div><div class="stats"><div><span>${T('Цена','Price')}</span><b>${price(c.price)}</b></div><div><span>${T('Капитализация','Market cap')}</span><b>${money(c.marketCap)}</b></div><div><span>${T('Объём 24ч','24h volume')}</span><b>${money(c.volume24)}</b></div><div><span>5M</span><b>${finite(c.change5m)?Number(c.change5m).toFixed(2)+'%':'—'}</b></div><div><span>15M</span><b>${finite(c.change15m)?Number(c.change15m).toFixed(2)+'%':'—'}</b></div><div><span>1H</span><b>${finite(c.change1h)?Number(c.change1h).toFixed(2)+'%':'—'}</b></div><div><span>1D</span><b>${finite(c.change24h)?Number(c.change24h).toFixed(2)+'%':'—'}</b></div><div><span>1M</span><b>${finite(c.change30d)?Number(c.change30d).toFixed(2)+'%':'—'}</b></div></div>`;sheet.classList.add('on')}
  load();setInterval(load,60000);
})();