// NEXUS ALPHA focused UX: VETTED DEX only + separate MEXC PUMP RADAR.
state.radarMode='vetted';state.vettedTokens=[];state.vettedUpdatedAt=0;
Object.assign(I18N.ru,{vettedDex:'VETTED DEX',mexcPump:'MEXC PUMP RADAR',allVetted:'ВСЕ ПРОВЕРЕННЫЕ',strongVetted:'СИЛЬНЫЕ',vettedEmpty:'Сейчас ни один старый DEX-токен не проходит все строгие проверки. Это нормально — фильтр специально жёсткий.',mexcPumpSub:'Потенциальные импульсы на MEXC: объём + сжатие + стакан + глубина. Уже улетевшие и тонкие рынки отбрасываются.'});
Object.assign(I18N.en,{vettedDex:'VETTED DEX',mexcPump:'MEXC PUMP RADAR',allVetted:'ALL VETTED',strongVetted:'STRONG',vettedEmpty:'No older DEX asset currently passes every strict check. That is expected — the gate is intentionally strict.',mexcPumpSub:'Potential MEXC impulses: volume + compression + order book + depth. Already-expanded and thin markets are rejected.'});

function installRadarModes(){
 if(document.getElementById('radarModeSwitch'))return;const deck=document.querySelector('.control-deck');if(!deck)return;
 deck.insertAdjacentHTML('beforebegin',`<section id="radarModeSwitch" class="radar-mode-switch"><button class="mode-btn active" data-mode="vetted"><span>◈</span><b>${esc(t('vettedDex'))}</b><small>${state.lang==='ru'?'30–365 дней · Verified · не на major CEX':'30–365 days · Verified · not on major CEX'}</small></button><button class="mode-btn mexc" data-mode="mexc"><span>↗</span><b>${esc(t('mexcPump'))}</b><small>${state.lang==='ru'?'потенциальный импульс · стакан · объём':'potential impulse · book · volume'}</small></button></section>`);
 document.querySelectorAll('.mode-btn').forEach(b=>b.onclick=()=>switchRadarMode(b.dataset.mode));
 rebuildVettedFilters();
}
function rebuildVettedFilters(){const f=$('tierFilters');if(!f)return;f.innerHTML=`<button class="filter active" data-tier="vetted">${esc(t('allVetted'))}</button><button class="filter" data-tier="strong">◆ ${esc(t('strongVetted'))}</button><button class="filter" data-tier="precex">PRE-CEX</button><button class="filter" data-tier="accumulation">ACCUMULATION</button><button class="filter" data-tier="projectnews">⚡ PROJECT NEWS</button><button class="filter" data-tier="watchlist">★ WATCHLIST</button>`;f.querySelectorAll('.filter').forEach(btn=>btn.onclick=()=>{f.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.tier=btn.dataset.tier;renderTokens()});state.tier='vetted'}
function switchRadarMode(mode){state.radarMode=mode==='mexc'?'mexc':'vetted';document.body.classList.toggle('mode-mexc',state.radarMode==='mexc');document.querySelectorAll('.mode-btn').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.radarMode));if(state.radarMode==='vetted'){state.tier='vetted';rebuildVettedFilters();renderTokens();renderVettedStats()}else{if(typeof refreshExtreme==='function')refreshExtreme();setTimeout(renderMexcPumpFocused,300)}}

function vettedListFiltered(){let list=[...(state.vettedTokens||[])];const q=state.search.trim().toLowerCase();if(q)list=list.filter(x=>[x.name,x.symbol,x.mint].some(v=>String(v||'').toLowerCase().includes(q)));if(state.tier==='strong')list=list.filter(x=>(x.vetted?.score||0)>=75);if(state.tier==='precex')list=list.filter(x=>x.vetted?.cex?.preCexCandidate||x.vetted?.cex?.projectClaimDetected);if(state.tier==='accumulation')list=list.filter(x=>(x.vetted?.setup?.accumulationPressure||0)>=65);if(state.tier==='projectnews')list=list.filter(x=>x.vetted?.cex?.projectClaimDetected);if(state.tier==='watchlist')list=list.filter(x=>state.watchlist.has(x.mint));if(state.risk!=='all')list=list.filter(x=>x.riskLevel===state.risk);if(state.sort==='new')list.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));else if(state.sort==='liq')list.sort((a,b)=>(b.dex?.liquidityUsd||0)-(a.dex?.liquidityUsd||0));else if(state.sort==='vol')list.sort((a,b)=>(b.dex?.volumeH1||0)-(a.dex?.volumeH1||0));else if(state.sort==='listing')list.sort((a,b)=>(b.vetted?.cex?.evidenceScore||0)-(a.vetted?.cex?.evidenceScore||0));else list.sort((a,b)=>(b.vetted?.score||0)-(a.vetted?.score||0));return list}
const focusedFilteredBase=filteredTokens;filteredTokens=function(){if(state.radarMode==='vetted')return vettedListFiltered();return focusedFilteredBase()};
const focusedEmptyBase=nexusEmptyMessage;nexusEmptyMessage=function(){if(state.radarMode==='vetted')return t('vettedEmpty');return focusedEmptyBase()};

function renderVettedStats(){if(state.radarMode!=='vetted')return;const list=state.vettedTokens||[],pre=list.filter(x=>x.vetted?.cex?.preCexCandidate||x.vetted?.cex?.projectClaimDetected).length,acc=list.filter(x=>(x.vetted?.setup?.accumulationPressure||0)>=65).length,avg=list.length?Math.round(list.reduce((s,x)=>s+(x.vetted?.ageDays||0),0)/list.length):0;const cards=document.querySelectorAll('#statGrid .stat-card');if(cards[0]){cards[0].querySelector('span').textContent=state.lang==='ru'?'МИН. ВОЗРАСТ':'MIN AGE';cards[0].querySelector('strong').textContent='30D';cards[0].querySelector('small').textContent=state.lang==='ru'?'новые скрыты':'new assets hidden'}if(cards[1]){cards[1].querySelector('span').textContent=state.lang==='ru'?'ПРОШЛИ GATE':'VETTED';cards[1].querySelector('strong').textContent=String(list.length);cards[1].querySelector('small').textContent=avg?`avg ${avg}d`:'strict gate'}if(cards[2]){cards[2].querySelector('span').textContent='PRE-CEX';cards[2].querySelector('strong').textContent=String(pre);cards[2].querySelector('small').textContent=state.lang==='ru'?'из проверенных':'among vetted'}if(cards[3]){cards[3].querySelector('span').textContent='ACCUMULATION';cards[3].querySelector('strong').textContent=String(acc);cards[3].querySelector('small').textContent='pressure ≥ 65'}}

async function refreshVetted(){try{const r=await fetch(`${API_BASE}/api/vetted?limit=300`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();state.vettedUpdatedAt=d.generatedAt||Date.now();state.vettedTokens=(d.tokens||[]).map(x=>({...x,score:x.vetted?.score??x.score,tier:(x.vetted?.score||0)>=85?'prime':(x.vetted?.score||0)>=70?'candidate':'watch'}));if(!state.data)state.data={tokens:[],alerts:[],sources:d.sources||{},stats:{}};const map=new Map((state.data.tokens||[]).map(x=>[x.mint,x]));for(const tk of state.vettedTokens){const old=map.get(tk.mint);if(old)Object.assign(old,tk);else state.data.tokens.push(tk)}state.data.sources={...(state.data.sources||{}),...(d.sources||{})};state.connected=true;renderTokens();renderSources();renderVettedStats();updateConnection()}catch(e){const box=$('emptyState');if(box&&state.radarMode==='vetted'&&!state.vettedTokens.length){box.classList.add('show');box.innerHTML=`<div class="empty-radar-mark">◈</div><strong>${esc(t('vettedEmpty'))}</strong><span>${esc(e.message)}</span>`}}}

function renderMexcPumpFocused(){if(state.radarMode!=='mexc')return;const box=$('mexcExtremeList');if(!box)return;const list=(state.extremeData?.mexc||[]).filter(m=>m.extreme&&!m.extreme.alreadyMoved&&m.extreme.riskGate!=='fail'&&(m.extreme.authenticity||0)>=50&&(m.extreme.score||0)>=40).sort((a,b)=>(b.extreme.score-a.extreme.score)||(b.extreme.authenticity-a.extreme.authenticity)).slice(0,25);const panel=document.querySelector('.mexc-panel .panel-head p');if(panel)panel.textContent=t('mexcPumpSub');box.innerHTML=list.length?list.map(m=>{const e=m.extreme,k=m.deep?.kline||{},gate=e.riskGate||'caution';return`<a class="mexc-row" href="${esc(m.url||'#')}" target="_blank" rel="noopener noreferrer"><div><strong>${esc(m.base)}/${esc(m.quote)}</strong><span>${fmtExtremePrice(m.price)} · 24h ${Number(m.change24h)>=0?'+':''}${Number(m.change24h||0).toFixed(1)}%</span></div><div><b>${e.score}</b><span>PUMP SETUP</span></div><div><b>${e.authenticity}</b><span>AUTH</span></div><div><b>${k.volAccel?Number(k.volAccel).toFixed(1)+'×':'—'}</b><span>VOL ACCEL</span></div><div><b>${m.deep?.bidAskImbalance2?Number(m.deep.bidAskImbalance2).toFixed(2):'—'}</b><span>BID/ASK</span></div><div><b>${fmtExtremeMoney(m.deep?.depth2Usd||0)}</b><span>DEPTH ±2%</span></div><span class="gate ${gateClass(gate)}">${esc(gate.toUpperCase())}</span></a>`}).join(''):`<div class="extreme-empty">${state.lang==='ru'?'Сейчас на MEXC нет рынка, который одновременно проходит фильтр структуры, глубины и authenticity. Ждём нормальный setup до движения.':'No MEXC market currently passes structure, depth and authenticity together. Waiting for a clean pre-move setup.'}</div>`}
const focusedExtremeRenderBase=renderExtremePanel;renderExtremePanel=function(){focusedExtremeRenderBase();renderMexcPumpFocused()};

const focusedDetailBase=renderDetail;renderDetail=function(tk){const cached=(state.vettedTokens||[]).find(x=>x.mint===tk.mint);if(cached?.vetted)tk={...tk,vetted:cached.vetted,jupiter:tk.jupiter||cached.jupiter,jupiterFlags:tk.jupiterFlags||cached.jupiterFlags};focusedDetailBase(tk);if(!tk.vetted)return;setTimeout(()=>{if(state.selectedMint!==tk.mint)return;const root=$('drawerContent');if(!root||root.querySelector('.vetted-proof'))return;const v=tk.vetted,j=tk.jupiter||{},cex=v.cex||{};root.querySelector('.drawer-score-grid')?.insertAdjacentHTML('beforebegin',`<section class="drawer-section vetted-proof"><div class="vetted-proof-head"><h3>◈ VETTED DEX PASS</h3><span>${v.ageDays} DAYS</span></div><div class="jup-grid"><div><span>JUPITER VERIFIED</span><strong class="jup-good">YES</strong></div><div><span>ORGANIC SCORE</span><strong>${Number(j.organicScore||0).toFixed(1)}</strong></div><div><span>JUP LIQUIDITY</span><strong>${formatMoney(j.liquidity||0)}</strong></div><div><span>DEX LIQUIDITY</span><strong>${formatMoney(tk.dex?.liquidityUsd||0)}</strong></div><div><span>MAJOR CEX</span><strong class="jup-good">NONE DETECTED</strong></div><div><span>VETTED SCORE</span><strong>${v.score}/100</strong></div></div><p class="drawer-note">${esc(state.lang==='ru'?'Допуск означает, что токен старше 30 дней и прошёл текущие Jupiter/on-chain/liquidity/CEX-фильтры. Это снижает очевидные риски, но не гарантирует отсутствие мошенничества или будущий рост.':'Eligibility means the asset is older than 30 days and passed current Jupiter/on-chain/liquidity/CEX checks. It reduces obvious risks but cannot guarantee safety or future appreciation.')}</p></section>`)},180)};

const focusedStyle=document.createElement('style');focusedStyle.textContent=`.radar-mode-switch{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 0 12px}.mode-btn{display:flex;align-items:center;gap:10px;text-align:left;border:1px solid var(--line);border-radius:12px;padding:13px 15px;background:rgba(255,255,255,.018);color:var(--text);cursor:pointer}.mode-btn>span{font-size:21px;color:#5de4ff}.mode-btn b,.mode-btn small{display:block}.mode-btn b{font-size:12px;letter-spacing:.08em}.mode-btn small{font-size:8px;color:var(--muted);margin-top:3px}.mode-btn.active{border-color:rgba(93,228,255,.45);box-shadow:inset 0 0 28px rgba(93,228,255,.055);background:rgba(93,228,255,.045)}.mode-btn.mexc.active{border-color:rgba(216,255,117,.42);box-shadow:inset 0 0 28px rgba(216,255,117,.04)}body:not(.mode-mexc) .extreme-workspace{display:none!important}body.mode-mexc .control-deck,body.mode-mexc .workspace{display:none!important}body.mode-mexc .extreme-workspace{display:block!important;margin-top:12px}body.mode-mexc .extreme-workspace .extreme-panel{display:none!important}body.mode-mexc .extreme-workspace .mexc-panel{display:block!important;width:100%}.vetted-proof{border-color:rgba(115,242,184,.22)!important;background:linear-gradient(135deg,rgba(115,242,184,.035),rgba(93,228,255,.02))}.vetted-proof-head{display:flex;align-items:center;justify-content:space-between}.vetted-proof-head h3{margin:0}.vetted-proof-head span{font-size:8px;color:#73f2b8;border:1px solid rgba(115,242,184,.25);padding:5px 7px;border-radius:999px}@media(max-width:700px){.radar-mode-switch{grid-template-columns:1fr}.mode-btn{padding:11px 12px}}`;document.head.appendChild(focusedStyle);

setTimeout(()=>{installRadarModes();switchRadarMode('vetted');refreshVetted()},1700);setInterval(refreshVetted,60_000);
