// Jupiter Trust UX — makes independent organic/verification evidence visible in every token drawer.
Object.assign(I18N.ru,{jupTrust:'JUPITER TRUST',jupPending:'Проверяем Jupiter organic/verification…',jupVerified:'Verified',jupOrganic:'Organic Score',jupLiq:'Jupiter Liquidity',jupHolders:'Holders',jupTop:'Top holders',jupWhy:'Почему статус понижен'});
Object.assign(I18N.en,{jupTrust:'JUPITER TRUST',jupPending:'Checking Jupiter organic/verification…',jupVerified:'Verified',jupOrganic:'Organic Score',jupLiq:'Jupiter Liquidity',jupHolders:'Holders',jupTop:'Top holders',jupWhy:'Why the status was reduced'});
const jupFlagText={ru:{jupiter_unverified:'Not Verified',jupiter_suspicious:'Suspicious token',jupiter_low_organic:'Low Organic Activity',jupiter_low_liquidity:'Low Liquidity',jupiter_top_holders_extreme:'High Supply Concentration',jupiter_new_listing:'New Listing',jupiter_pending:'Jupiter check pending'},en:{jupiter_unverified:'Not Verified',jupiter_suspicious:'Suspicious token',jupiter_low_organic:'Low Organic Activity',jupiter_low_liquidity:'Low Liquidity',jupiter_top_holders_extreme:'High Supply Concentration',jupiter_new_listing:'New Listing',jupiter_pending:'Jupiter check pending'}};
function jupLabel(f){return jupFlagText[state.lang]?.[f]||String(f||'').replaceAll('_',' ')}
function jupGate(flags,j){if(!j)return'CAUTION';if(flags.includes('jupiter_suspicious')||flags.includes('jupiter_top_holders_extreme')||(flags.includes('jupiter_low_organic')&&flags.includes('jupiter_low_liquidity')))return'FAIL';if(flags.some(x=>['jupiter_unverified','jupiter_low_organic','jupiter_low_liquidity'].includes(x)))return'CAUTION';return'PASS'}
function renderJupiterTrust(root,payload){
 const old=root.querySelector('.jupiter-trust-section');if(old)old.remove();const j=payload?.jupiter||null,flags=payload?.flags||payload?.jupiterFlags||[],gate=jupGate(flags,j),anchor=root.querySelector('.extreme-detail')||root.querySelector('.drawer-score-grid');
 const body=!j?`<p class="drawer-note"><span class="spinner tiny"></span> ${esc(t('jupPending'))}</p>`:`<div class="jup-grid"><div><span>${esc(t('jupVerified'))}</span><strong class="${j.isVerified?'jup-good':'jup-warn'}">${j.isVerified?'YES':'NO'}</strong></div><div><span>${esc(t('jupOrganic'))}</span><strong>${Number(j.organicScore||0).toFixed(1)}</strong><small>${esc(j.organicScoreLabel||'—')}</small></div><div><span>${esc(t('jupLiq'))}</span><strong>${formatMoney(j.liquidity||0)}</strong></div><div><span>${esc(t('jupHolders'))}</span><strong>${numFmt(j.holderCount||0)}</strong></div><div><span>${esc(t('jupTop'))}</span><strong>${j.audit?.topHoldersPercentage?Number(j.audit.topHoldersPercentage).toFixed(1)+'%':'—'}</strong></div><div><span>TRUST GATE</span><strong class="${gate==='PASS'?'jup-good':gate==='FAIL'?'jup-bad':'jup-warn'}">${gate}</strong></div></div><div class="jup-warnings">${flags.length?flags.map(f=>`<span class="jup-warning">⚠ ${esc(jupLabel(f))}</span>`).join(''):`<span class="jup-clean">✓ No Jupiter trust warning in current token data</span>`}</div><p class="drawer-note">${esc(state.lang==='ru'?'Not Verified не означает мошенничество само по себе. Но Low Organic + Low Liquidity блокируют EXTREME/PRIME; suspicious/high concentration дают FAIL.':'Not Verified alone does not mean fraud. Low Organic + Low Liquidity block EXTREME/PRIME; suspicious/high concentration produce FAIL.')}</p>`;
 const html=`<section class="drawer-section jupiter-trust-section"><div class="jup-title"><h3>♃ ${esc(t('jupTrust'))}</h3><span class="gate ${gate==='PASS'?'gate-pass':gate==='FAIL'?'gate-fail':'gate-caution'}">${gate}</span></div>${body}</section>`;
 if(anchor)anchor.insertAdjacentHTML('afterend',html);else root.insertAdjacentHTML('beforeend',html);
}
async function refreshJupiterForDrawer(tk){
 const mint=tk?.mint;if(!mint)return;const root=$('drawerContent');if(!root)return;renderJupiterTrust(root,{jupiter:tk.jupiter||null,flags:tk.jupiterFlags||[]});
 try{const r=await fetch(`${API_BASE}/api/jupiter-risk/${encodeURIComponent(mint)}`,{cache:'no-store'});if(!r.ok)throw new Error('Jupiter');const d=await r.json();if(state.selectedMint!==mint)return;const all=[...(state.data?.tokens||[]),...(state.alphaExtendedTokens||[])];for(const x of all.filter(x=>x.mint===mint)){x.jupiter=d.jupiter;x.jupiterFlags=d.flags;x.score=d.score;x.risk=d.risk;x.riskLevel=d.riskLevel;if(d.extreme)x.extreme=d.extreme}renderJupiterTrust($('drawerContent'),d);renderTokens();}catch{if(state.selectedMint===mint){const sec=$('drawerContent')?.querySelector('.jupiter-trust-section .drawer-note');if(sec)sec.textContent=state.lang==='ru'?'Jupiter временно недоступен — PASS не выдаётся до проверки.':'Jupiter temporarily unavailable — PASS is withheld until checked.'}}
}
const jupRenderDetailBase=renderDetail;renderDetail=function(tk){jupRenderDetailBase(tk);setTimeout(()=>refreshJupiterForDrawer(tk),120)};
const jupRenderTokensBase=renderTokens;renderTokens=function(){jupRenderTokensBase();document.querySelectorAll('#tokenBody tr[data-mint]').forEach(row=>{const mint=row.dataset.mint,tk=[...(state.data?.tokens||[]),...(state.alphaExtendedTokens||[])].find(x=>x.mint===mint);if(!tk)return;const flags=tk.jupiterFlags||[];if(!flags.length)return;const cell=row.querySelector('td:last-child');if(!cell||cell.querySelector('.jup-table-chip'))return;const severe=flags.includes('jupiter_suspicious')||(flags.includes('jupiter_low_organic')&&flags.includes('jupiter_low_liquidity'));cell.insertAdjacentHTML('beforeend',`<div class="edge-chip-row"><span class="edge-chip jup-table-chip ${severe?'gate-fail':'gate-caution'}">♃ ${severe?'JUP FAIL':'JUP CHECK'}</span></div>`)})};
const st=document.createElement('style');st.textContent=`.jup-title{display:flex;align-items:center;justify-content:space-between}.jup-title h3{margin:0}.jup-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.jup-grid>div{border:1px solid var(--line);border-radius:10px;padding:10px;background:rgba(255,255,255,.018)}.jup-grid span,.jup-grid small{display:block;color:var(--muted);font-size:8px}.jup-grid strong{display:block;font-size:15px;margin-top:5px}.jup-good{color:#73f2b8!important}.jup-warn{color:#ffd17b!important}.jup-bad{color:#ff8383!important}.jup-warnings{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.jup-warning,.jup-clean{font-size:8px;padding:5px 7px;border-radius:999px;border:1px solid rgba(255,209,123,.25);color:#ffd17b;background:rgba(255,209,123,.04)}.jup-clean{border-color:rgba(115,242,184,.25);color:#73f2b8}.spinner.tiny{display:inline-block;width:11px;height:11px;border-width:1px}@media(max-width:760px){.jup-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(st);
